// <copyright file="AccountGroupShareAction.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// AccountGroupShareAction.
    /// </summary>
    public class AccountGroupShareAction
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountGroupShareAction"/> class.
        /// </summary>
        public AccountGroupShareAction()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountGroupShareAction"/> class.
        /// </summary>
        /// <param name="notify">notify.</param>
        public AccountGroupShareAction(
            Models.Notify notify = null)
        {
            this.Notify = notify;
        }

        /// <summary>
        /// Gets or sets Notify.
        /// </summary>
        [JsonProperty("notify", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Notify Notify { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccountGroupShareAction : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AccountGroupShareAction other &&
                (this.Notify == null && other.Notify == null ||
                 this.Notify?.Equals(other.Notify) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Notify = {(this.Notify == null ? "null" : this.Notify.ToString())}");
        }
    }
}