// <copyright file="AccountGroupShareObject.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// AccountGroupShareObject.
    /// </summary>
    public class AccountGroupShareObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountGroupShareObject"/> class.
        /// </summary>
        public AccountGroupShareObject()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountGroupShareObject"/> class.
        /// </summary>
        /// <param name="accountGroupShare">accountGroupShare.</param>
        public AccountGroupShareObject(
            Models.AccountGroupShareIndividual1 accountGroupShare = null)
        {
            this.AccountGroupShare = accountGroupShare;
        }

        /// <summary>
        /// Gets or sets AccountGroupShare.
        /// </summary>
        [JsonProperty("accountGroupShare", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AccountGroupShareIndividual1 AccountGroupShare { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccountGroupShareObject : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AccountGroupShareObject other &&
                (this.AccountGroupShare == null && other.AccountGroupShare == null ||
                 this.AccountGroupShare?.Equals(other.AccountGroupShare) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountGroupShare = {(this.AccountGroupShare == null ? "null" : this.AccountGroupShare.ToString())}");
        }
    }
}