// <copyright file="AccountLevelFilter.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// AccountLevelFilter.
    /// </summary>
    public class AccountLevelFilter
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountLevelFilter"/> class.
        /// </summary>
        public AccountLevelFilter()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountLevelFilter"/> class.
        /// </summary>
        /// <param name="separateOrCombined">separateOrCombined.</param>
        /// <param name="accountNames">accountNames.</param>
        public AccountLevelFilter(
            string separateOrCombined = null,
            Models.Accountnames accountNames = null)
        {
            this.SeparateOrCombined = separateOrCombined;
            this.AccountNames = accountNames;
        }

        /// <summary>
        /// Determines whether or not to aggregate usage of multiple accounts together, or separate by account. If this is null or not present, then the trigger will be for an individual line.
        /// </summary>
        [JsonProperty("separateOrCombined", NullValueHandling = NullValueHandling.Ignore)]
        public string SeparateOrCombined { get; set; }

        /// <summary>
        /// Gets or sets AccountNames.
        /// </summary>
        [JsonProperty("accountNames", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Accountnames AccountNames { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccountLevelFilter : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AccountLevelFilter other &&
                (this.SeparateOrCombined == null && other.SeparateOrCombined == null ||
                 this.SeparateOrCombined?.Equals(other.SeparateOrCombined) == true) &&
                (this.AccountNames == null && other.AccountNames == null ||
                 this.AccountNames?.Equals(other.AccountNames) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"SeparateOrCombined = {this.SeparateOrCombined ?? "null"}");
            toStringOutput.Add($"AccountNames = {(this.AccountNames == null ? "null" : this.AccountNames.ToString())}");
        }
    }
}