// <copyright file="Accountid.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// Accountid.
    /// </summary>
    public class Accountid
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Accountid"/> class.
        /// </summary>
        public Accountid()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Accountid"/> class.
        /// </summary>
        /// <param name="accountName">accountName.</param>
        /// <param name="mtasAccountNumber">mtasAccountNumber.</param>
        public Accountid(
            string accountName = null,
            string mtasAccountNumber = null)
        {
            this.AccountName = accountName;
            this.MtasAccountNumber = mtasAccountNumber;
        }

        /// <summary>
        /// The numeric name of the account and must include leading zeroes
        /// </summary>
        [JsonProperty("accountName", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountName { get; set; }

        /// <summary>
        /// Gets or sets MtasAccountNumber.
        /// </summary>
        [JsonProperty("mtasAccountNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string MtasAccountNumber { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Accountid : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Accountid other &&
                (this.AccountName == null && other.AccountName == null ||
                 this.AccountName?.Equals(other.AccountName) == true) &&
                (this.MtasAccountNumber == null && other.MtasAccountNumber == null ||
                 this.MtasAccountNumber?.Equals(other.MtasAccountNumber) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountName = {this.AccountName ?? "null"}");
            toStringOutput.Add($"MtasAccountNumber = {this.MtasAccountNumber ?? "null"}");
        }
    }
}