// <copyright file="AsphaltOrTar.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// AsphaltOrTar.
    /// </summary>
    public class AsphaltOrTar
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AsphaltOrTar"/> class.
        /// </summary>
        public AsphaltOrTar()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AsphaltOrTar"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        public AsphaltOrTar(
            Models.Type7Enum? type = null)
        {
            this.Type = type;
        }

        /// <summary>
        /// Indicates the type of asphalt or tar.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Type7Enum? Type { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AsphaltOrTar : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AsphaltOrTar other &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {(this.Type == null ? "null" : this.Type.ToString())}");
        }
    }
}