// <copyright file="CauseCodeChoice3.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// CauseCodeChoice3.
    /// </summary>
    public class CauseCodeChoice3
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CauseCodeChoice3"/> class.
        /// </summary>
        public CauseCodeChoice3()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CauseCodeChoice3"/> class.
        /// </summary>
        /// <param name="impassability5">impassability5.</param>
        public CauseCodeChoice3(
            int impassability5)
        {
            this.Impassability5 = impassability5;
        }

        /// <summary>
        /// The value shall be set to:
        /// - 0 `unavailable`              - in case further detailed information about the unmanaged road blockage is unavailable,
        /// - 1 `flooding          `       - in case the road is affected by flooding,
        /// - 2 `dangerOfAvalanches`       - in case the road is at risk of being affected or blocked by avalanches,
        /// - 3 `blastingOfAvalanches`     - in case there is an active blasting of avalanches on or near the road,
        /// - 4 `landslips`                - in case the road is affected by landslips,
        /// - 5 `chemicalSpillage`         - in case the road is affected by chemical spillage,
        /// - 6 `winterClosure`            - in case the road is impassable due to a winter closure.
        /// - 7 `sinkhole`                 - in case the road is impassable due to large holes in the road surface.
        /// - 8 `earthquakeDamage`         - in case the road is obstructed or partially obstructed because of damage caused by an earthquake.
        /// - 9 `fallenTrees`              - in case the road is obstructed or partially obstructed by one or more fallen trees.
        /// - 10 `rockfalls`               - in case the road is obstructed or partially obstructed due to fallen rocks.
        /// - 11 `sewerOverflow`           - in case the road is obstructed or partially obstructed by overflows from one or more sewers.
        /// - 12 `stormDamage`             - in case the road is obstructed or partially obstructed by debris caused by strong winds.
        /// - 13 `subsidence`              - in case the road surface has sunken or collapsed in places.
        /// - 14 `burstPipe`               - in case the road surface has sunken or collapsed in places due to burst pipes.
        /// - 15 `burstWaterMain`          - in case the road is obstructed due to local flooding and/or subsidence.
        /// - 16 `fallenPowerCables`       - in case the road is obstructed or partly obstructed by one or more fallen power cables.
        /// - 17 `snowDrifts`              - in case the road is obstructed or partially obstructed by snow drifting in progress or patches of deep snow due to earlier drifting.
        /// - 15-255                       - are reserved for future usage.
        /// </summary>
        [JsonProperty("impassability5")]
        [JsonRequired]
        public int Impassability5 { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CauseCodeChoice3 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CauseCodeChoice3 other &&
                (this.Impassability5.Equals(other.Impassability5));
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Impassability5 = {this.Impassability5}");
        }
    }
}