// <copyright file="ChangePlanDetails.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// ChangePlanDetails.
    /// </summary>
    public class ChangePlanDetails
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChangePlanDetails"/> class.
        /// </summary>
        public ChangePlanDetails()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChangePlanDetails"/> class.
        /// </summary>
        /// <param name="toCarrierServicePlanCode">toCarrierServicePlanCode.</param>
        public ChangePlanDetails(
            string toCarrierServicePlanCode = null)
        {
            this.ToCarrierServicePlanCode = toCarrierServicePlanCode;
        }

        /// <summary>
        /// Gets or sets ToCarrierServicePlanCode.
        /// </summary>
        [JsonProperty("toCarrierServicePlanCode", NullValueHandling = NullValueHandling.Ignore)]
        public string ToCarrierServicePlanCode { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ChangePlanDetails : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ChangePlanDetails other &&
                (this.ToCarrierServicePlanCode == null && other.ToCarrierServicePlanCode == null ||
                 this.ToCarrierServicePlanCode?.Equals(other.ToCarrierServicePlanCode) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ToCarrierServicePlanCode = {this.ToCarrierServicePlanCode ?? "null"}");
        }
    }
}