// <copyright file="ConditionActionEnum.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// ConditionActionEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ConditionActionEnum
    {
        /// <summary>
        /// Notify.
        /// </summary>
        [EnumMember(Value = "notify")]
        Notify,

        /// <summary>
        /// Suspend.
        /// </summary>
        [EnumMember(Value = "suspend")]
        Suspend,

        /// <summary>
        /// ChangePricePlan.
        /// </summary>
        [EnumMember(Value = "changePricePlan")]
        ChangePricePlan
    }
}