// <copyright file="Content4.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;
using Verizon.Standard.Models.Containers;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// Content4.
    /// </summary>
    public class Content4
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Content4"/> class.
        /// </summary>
        public Content4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Content4"/> class.
        /// </summary>
        /// <param name="exitService">exitService.</param>
        public Content4(
            List<TextPhraseOrITIS2> exitService)
        {
            this.ExitService = exitService;
        }

        /// <summary>
        /// List of roadside available services.
        /// </summary>
        [JsonProperty("exitService")]
        [JsonRequired]
        public List<TextPhraseOrITIS2> ExitService { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Content4 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Content4 other &&
                (this.ExitService == null && other.ExitService == null ||
                 this.ExitService?.Equals(other.ExitService) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ExitService = {(this.ExitService == null ? "null" : this.ExitService.ToString())}");
        }
    }
}