// <copyright file="CredentialsRequest.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// CredentialsRequest.
    /// </summary>
    public class CredentialsRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CredentialsRequest"/> class.
        /// </summary>
        public CredentialsRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CredentialsRequest"/> class.
        /// </summary>
        /// <param name="eCPD">ECPD.</param>
        /// <param name="accountNumber">accountNumber.</param>
        /// <param name="items">items.</param>
        public CredentialsRequest(
            string eCPD,
            string accountNumber,
            List<Models.DeviceCredentialRequestItem> items)
        {
            this.ECPD = eCPD;
            this.AccountNumber = accountNumber;
            this.Items = items;
        }

        /// <summary>
        /// Enterprise Customer Profile ID
        /// </summary>
        [JsonProperty("ECPD")]
        public string ECPD { get; set; }

        /// <summary>
        /// Billing Account Number
        /// </summary>
        [JsonProperty("accountNumber")]
        public string AccountNumber { get; set; }

        /// <summary>
        /// List of devices (1-50 items)
        /// </summary>
        [JsonProperty("items")]
        public List<Models.DeviceCredentialRequestItem> Items { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CredentialsRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CredentialsRequest other &&
                (this.ECPD == null && other.ECPD == null ||
                 this.ECPD?.Equals(other.ECPD) == true) &&
                (this.AccountNumber == null && other.AccountNumber == null ||
                 this.AccountNumber?.Equals(other.AccountNumber) == true) &&
                (this.Items == null && other.Items == null ||
                 this.Items?.Equals(other.Items) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ECPD = {this.ECPD ?? "null"}");
            toStringOutput.Add($"AccountNumber = {this.AccountNumber ?? "null"}");
            toStringOutput.Add($"Items = {(this.Items == null ? "null" : $"[{string.Join(", ", this.Items)} ]")}");
        }
    }
}