// <copyright file="DenmPayload.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// DenmPayload.
    /// </summary>
    public class DenmPayload
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DenmPayload"/> class.
        /// </summary>
        public DenmPayload()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DenmPayload"/> class.
        /// </summary>
        /// <param name="management">management.</param>
        /// <param name="situation">situation.</param>
        public DenmPayload(
            Models.Management management,
            Models.Situation situation = null)
        {
            this.Management = management;
            this.Situation = situation;
        }

        /// <summary>
        /// This represent the management container describing the meta information about the event, such as the detection time, the event's location, the source of the event, and the notification distance.
        /// </summary>
        [JsonProperty("management")]
        public Models.Management Management { get; set; }

        /// <summary>
        /// This represents the situation container describing the event and the reliability of the detection source.
        /// </summary>
        [JsonProperty("situation", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Situation Situation { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"DenmPayload : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is DenmPayload other &&
                (this.Management == null && other.Management == null ||
                 this.Management?.Equals(other.Management) == true) &&
                (this.Situation == null && other.Situation == null ||
                 this.Situation?.Equals(other.Situation) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Management = {(this.Management == null ? "null" : this.Management.ToString())}");
            toStringOutput.Add($"Situation = {(this.Situation == null ? "null" : this.Situation.ToString())}");
        }
    }
}