// <copyright file="DescriptionOfRoadSurfaceGravel.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// DescriptionOfRoadSurfaceGravel.
    /// </summary>
    public class DescriptionOfRoadSurfaceGravel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionOfRoadSurfaceGravel"/> class.
        /// </summary>
        public DescriptionOfRoadSurfaceGravel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionOfRoadSurfaceGravel"/> class.
        /// </summary>
        /// <param name="gravel">gravel.</param>
        public DescriptionOfRoadSurfaceGravel(
            Models.Gravel gravel)
        {
            this.Gravel = gravel;
        }

        /// <summary>
        /// Indicates the surface of the roadway is gravel.
        /// </summary>
        [JsonProperty("gravel")]
        [JsonRequired]
        public Models.Gravel Gravel { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"DescriptionOfRoadSurfaceGravel : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is DescriptionOfRoadSurfaceGravel other &&
                (this.Gravel == null && other.Gravel == null ||
                 this.Gravel?.Equals(other.Gravel) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Gravel = {(this.Gravel == null ? "null" : this.Gravel.ToString())}");
        }
    }
}