// <copyright file="DescriptionOfRoadSurfaceSnow.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// DescriptionOfRoadSurfaceSnow.
    /// </summary>
    public class DescriptionOfRoadSurfaceSnow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionOfRoadSurfaceSnow"/> class.
        /// </summary>
        public DescriptionOfRoadSurfaceSnow()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionOfRoadSurfaceSnow"/> class.
        /// </summary>
        /// <param name="snow">snow.</param>
        public DescriptionOfRoadSurfaceSnow(
            Models.Snow snow)
        {
            this.Snow = snow;
        }

        /// <summary>
        /// Indicates the surface of the roadway is snow.
        /// </summary>
        [JsonProperty("snow")]
        [JsonRequired]
        public Models.Snow Snow { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"DescriptionOfRoadSurfaceSnow : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is DescriptionOfRoadSurfaceSnow other &&
                (this.Snow == null && other.Snow == null ||
                 this.Snow?.Equals(other.Snow) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Snow = {(this.Snow == null ? "null" : this.Snow.ToString())}");
        }
    }
}