// <copyright file="DescriptionOfRoadSurfaceCinders.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// DescriptionOfRoadSurfaceCinders.
    /// </summary>
    public class DescriptionOfRoadSurfaceCinders
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionOfRoadSurfaceCinders"/> class.
        /// </summary>
        public DescriptionOfRoadSurfaceCinders()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionOfRoadSurfaceCinders"/> class.
        /// </summary>
        /// <param name="cinders">cinders.</param>
        public DescriptionOfRoadSurfaceCinders(
            Models.Cinders cinders)
        {
            this.Cinders = cinders;
        }

        /// <summary>
        /// Indicates the surface of the roadway is cinders.
        /// </summary>
        [JsonProperty("cinders")]
        [JsonRequired]
        public Models.Cinders Cinders { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"DescriptionOfRoadSurfaceCinders : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is DescriptionOfRoadSurfaceCinders other &&
                (this.Cinders == null && other.Cinders == null ||
                 this.Cinders?.Equals(other.Cinders) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Cinders = {(this.Cinders == null ? "null" : this.Cinders.ToString())}");
        }
    }
}