// <copyright file="DescriptionOfRoadSurfaceIce.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// DescriptionOfRoadSurfaceIce.
    /// </summary>
    public class DescriptionOfRoadSurfaceIce
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionOfRoadSurfaceIce"/> class.
        /// </summary>
        public DescriptionOfRoadSurfaceIce()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionOfRoadSurfaceIce"/> class.
        /// </summary>
        /// <param name="ice">ice.</param>
        public DescriptionOfRoadSurfaceIce(
            Models.Ice ice)
        {
            this.Ice = ice;
        }

        /// <summary>
        /// Indicates the surface of the roadway is ice.
        /// </summary>
        [JsonProperty("ice")]
        [JsonRequired]
        public Models.Ice Ice { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"DescriptionOfRoadSurfaceIce : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is DescriptionOfRoadSurfaceIce other &&
                (this.Ice == null && other.Ice == null ||
                 this.Ice?.Equals(other.Ice) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Ice = {(this.Ice == null ? "null" : this.Ice.ToString())}");
        }
    }
}