// <copyright file="DeviceGroupFilter.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// DeviceGroupFilter.
    /// </summary>
    public class DeviceGroupFilter
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceGroupFilter"/> class.
        /// </summary>
        public DeviceGroupFilter()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceGroupFilter"/> class.
        /// </summary>
        /// <param name="deviceGroupName">deviceGroupName.</param>
        /// <param name="individualOrCombined">IndividualOrCombined.</param>
        /// <param name="accountName">accountName.</param>
        public DeviceGroupFilter(
            string deviceGroupName = null,
            string individualOrCombined = null,
            string accountName = null)
        {
            this.DeviceGroupName = deviceGroupName;
            this.IndividualOrCombined = individualOrCombined;
            this.AccountName = accountName;
        }

        /// <summary>
        /// Gets or sets DeviceGroupName.
        /// </summary>
        [JsonProperty("deviceGroupName", NullValueHandling = NullValueHandling.Ignore)]
        public string DeviceGroupName { get; set; }

        /// <summary>
        /// Gets or sets IndividualOrCombined.
        /// </summary>
        [JsonProperty("IndividualOrCombined", NullValueHandling = NullValueHandling.Ignore)]
        public string IndividualOrCombined { get; set; }

        /// <summary>
        /// The numeric name of the account and must include leading zeroes
        /// </summary>
        [JsonProperty("accountName", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountName { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"DeviceGroupFilter : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is DeviceGroupFilter other &&
                (this.DeviceGroupName == null && other.DeviceGroupName == null ||
                 this.DeviceGroupName?.Equals(other.DeviceGroupName) == true) &&
                (this.IndividualOrCombined == null && other.IndividualOrCombined == null ||
                 this.IndividualOrCombined?.Equals(other.IndividualOrCombined) == true) &&
                (this.AccountName == null && other.AccountName == null ||
                 this.AccountName?.Equals(other.AccountName) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DeviceGroupName = {this.DeviceGroupName ?? "null"}");
            toStringOutput.Add($"IndividualOrCombined = {this.IndividualOrCombined ?? "null"}");
            toStringOutput.Add($"AccountName = {this.AccountName ?? "null"}");
        }
    }
}