// <copyright file="DropResponseItem.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// DropResponseItem.
    /// </summary>
    public class DropResponseItem
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DropResponseItem"/> class.
        /// </summary>
        public DropResponseItem()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DropResponseItem"/> class.
        /// </summary>
        /// <param name="imei">imei.</param>
        public DropResponseItem(
            string imei = null)
        {
            this.Imei = imei;
        }

        /// <summary>
        /// Gets or sets Imei.
        /// </summary>
        [JsonProperty("imei", NullValueHandling = NullValueHandling.Ignore)]
        public string Imei { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"DropResponseItem : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is DropResponseItem other &&
                (this.Imei == null && other.Imei == null ||
                 this.Imei?.Equals(other.Imei) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Imei = {this.Imei ?? "null"}");
        }
    }
}