// <copyright file="DtoDeviceActionSetResponse.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// DtoDeviceActionSetResponse.
    /// </summary>
    public class DtoDeviceActionSetResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DtoDeviceActionSetResponse"/> class.
        /// </summary>
        public DtoDeviceActionSetResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DtoDeviceActionSetResponse"/> class.
        /// </summary>
        /// <param name="actionresult">actionresult.</param>
        public DtoDeviceActionSetResponse(
            List<Models.ActionResultwithDeviceConfig> actionresult = null)
        {
            this.Actionresult = actionresult;
        }

        /// <summary>
        /// Gets or sets Actionresult.
        /// </summary>
        [JsonProperty("actionresult", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ActionResultwithDeviceConfig> Actionresult { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"DtoDeviceActionSetResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is DtoDeviceActionSetResponse other &&
                (this.Actionresult == null && other.Actionresult == null ||
                 this.Actionresult?.Equals(other.Actionresult) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Actionresult = {(this.Actionresult == null ? "null" : $"[{string.Join(", ", this.Actionresult)} ]")}");
        }
    }
}