// <copyright file="DtoResourceidentifier.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// DtoResourceidentifier.
    /// </summary>
    public class DtoResourceidentifier
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DtoResourceidentifier"/> class.
        /// </summary>
        public DtoResourceidentifier()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DtoResourceidentifier"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        public DtoResourceidentifier(
            string id = null)
        {
            this.Id = id;
        }

        /// <summary>
        /// UUID of the user record, assigned at creation
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"DtoResourceidentifier : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is DtoResourceidentifier other &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
        }
    }
}