// <copyright file="EtxGeoFence.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// EtxGeoFence.
    /// </summary>
    public class EtxGeoFence
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EtxGeoFence"/> class.
        /// </summary>
        public EtxGeoFence()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EtxGeoFence"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="features">features.</param>
        public EtxGeoFence(
            Models.TypeEnum type,
            List<Models.EtxFeature> features)
        {
            this.Type = type;
            this.Features = features;
        }

        /// <summary>
        /// Gets or sets Type.
        /// </summary>
        [JsonProperty("type")]
        public Models.TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or sets Features.
        /// </summary>
        [JsonProperty("features")]
        public List<Models.EtxFeature> Features { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"EtxGeoFence : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is EtxGeoFence other &&
                (this.Type.Equals(other.Type)) &&
                (this.Features == null && other.Features == null ||
                 this.Features?.Equals(other.Features) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {this.Type}");
            toStringOutput.Add($"Features = {(this.Features == null ? "null" : $"[{string.Join(", ", this.Features)} ]")}");
        }
    }
}