// <copyright file="EventType.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;
using Verizon.Standard.Models.Containers;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// EventType.
    /// </summary>
    public class EventType
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventType"/> class.
        /// </summary>
        public EventType()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventType"/> class.
        /// </summary>
        /// <param name="ccAndScc">ccAndScc.</param>
        public EventType(
            CauseCodeChoice6 ccAndScc = null)
        {
            this.CcAndScc = ccAndScc;
        }

        /// <summary>
        /// The main cause of a detected event. Each entry is of a different type and represents the sub cause code.
        /// </summary>
        [JsonProperty("ccAndScc", NullValueHandling = NullValueHandling.Ignore)]
        public CauseCodeChoice6 CcAndScc { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"EventType : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is EventType other &&
                (this.CcAndScc == null && other.CcAndScc == null ||
                 this.CcAndScc?.Equals(other.CcAndScc) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CcAndScc = {(this.CcAndScc == null ? "null" : this.CcAndScc.ToString())}");
        }
    }
}