// <copyright file="FrictionInformation.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;
using Verizon.Standard.Models.Containers;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// FrictionInformation.
    /// </summary>
    public class FrictionInformation
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FrictionInformation"/> class.
        /// </summary>
        public FrictionInformation()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FrictionInformation"/> class.
        /// </summary>
        /// <param name="roadSurfaceDescription">roadSurfaceDescription.</param>
        public FrictionInformation(
            DescriptionOfRoadSurface roadSurfaceDescription)
        {
            this.RoadSurfaceDescription = roadSurfaceDescription;
        }

        /// <summary>
        /// Indicates the composition of the surface of the roadway for use in estimation of friction.
        /// </summary>
        [JsonProperty("roadSurfaceDescription")]
        public DescriptionOfRoadSurface RoadSurfaceDescription { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FrictionInformation : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is FrictionInformation other &&
                (this.RoadSurfaceDescription == null && other.RoadSurfaceDescription == null ||
                 this.RoadSurfaceDescription?.Equals(other.RoadSurfaceDescription) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"RoadSurfaceDescription = {(this.RoadSurfaceDescription == null ? "null" : this.RoadSurfaceDescription.ToString())}");
        }
    }
}