// <copyright file="GetAccountInformationResponseforplanner.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// GetAccountInformationResponseforplanner.
    /// </summary>
    public class GetAccountInformationResponseforplanner
    {
        private string accountNumber;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "accountNumber", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="GetAccountInformationResponseforplanner"/> class.
        /// </summary>
        public GetAccountInformationResponseforplanner()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetAccountInformationResponseforplanner"/> class.
        /// </summary>
        /// <param name="accountName">accountName.</param>
        /// <param name="accountNumber">accountNumber.</param>
        /// <param name="carriers">carriers.</param>
        /// <param name="features">features.</param>
        /// <param name="ipPools">ipPools.</param>
        /// <param name="isProvisioningAllowed">isProvisioningAllowed.</param>
        /// <param name="organizationName">organizationName.</param>
        /// <param name="servicePlans">servicePlans.</param>
        public GetAccountInformationResponseforplanner(
            string accountName = null,
            string accountNumber = null,
            List<string> carriers = null,
            List<string> features = null,
            List<Models.IPPoolforplanner> ipPools = null,
            bool? isProvisioningAllowed = null,
            string organizationName = null,
            List<Models.ServicePlanResponseforplanner> servicePlans = null)
        {
            this.AccountName = accountName;

            if (accountNumber != null)
            {
                this.AccountNumber = accountNumber;
            }
            this.Carriers = carriers;
            this.Features = features;
            this.IpPools = ipPools;
            this.IsProvisioningAllowed = isProvisioningAllowed;
            this.OrganizationName = organizationName;
            this.ServicePlans = servicePlans;
        }

        /// <summary>
        /// Gets or sets AccountName.
        /// </summary>
        [JsonProperty("accountName", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountName { get; set; }

        /// <summary>
        /// The numeric name of the account, including leading zeros.
        /// </summary>
        [JsonProperty("accountNumber")]
        public string AccountNumber
        {
            get
            {
                return this.accountNumber;
            }

            set
            {
                this.shouldSerialize["accountNumber"] = true;
                this.accountNumber = value;
            }
        }

        /// <summary>
        /// The list of carrier names with profiles.
        /// </summary>
        [JsonProperty("carriers", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Carriers { get; set; }

        /// <summary>
        /// a list of features associated with the resident profiles.
        /// </summary>
        [JsonProperty("features", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Features { get; set; }

        /// <summary>
        /// Gets or sets IpPools.
        /// </summary>
        [JsonProperty("ipPools", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.IPPoolforplanner> IpPools { get; set; }

        /// <summary>
        /// A flag indicating if provisioning is allowed (true) or provisioning is locked (false).
        /// </summary>
        [JsonProperty("isProvisioningAllowed", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsProvisioningAllowed { get; set; }

        /// <summary>
        /// The user assigned organization name.
        /// </summary>
        [JsonProperty("organizationName", NullValueHandling = NullValueHandling.Ignore)]
        public string OrganizationName { get; set; }

        /// <summary>
        /// A list of service plans associated with the resident profiles.
        /// </summary>
        [JsonProperty("servicePlans", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ServicePlanResponseforplanner> ServicePlans { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"GetAccountInformationResponseforplanner : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountNumber()
        {
            this.shouldSerialize["accountNumber"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountNumber()
        {
            return this.shouldSerialize["accountNumber"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is GetAccountInformationResponseforplanner other &&
                (this.AccountName == null && other.AccountName == null ||
                 this.AccountName?.Equals(other.AccountName) == true) &&
                (this.AccountNumber == null && other.AccountNumber == null ||
                 this.AccountNumber?.Equals(other.AccountNumber) == true) &&
                (this.Carriers == null && other.Carriers == null ||
                 this.Carriers?.Equals(other.Carriers) == true) &&
                (this.Features == null && other.Features == null ||
                 this.Features?.Equals(other.Features) == true) &&
                (this.IpPools == null && other.IpPools == null ||
                 this.IpPools?.Equals(other.IpPools) == true) &&
                (this.IsProvisioningAllowed == null && other.IsProvisioningAllowed == null ||
                 this.IsProvisioningAllowed?.Equals(other.IsProvisioningAllowed) == true) &&
                (this.OrganizationName == null && other.OrganizationName == null ||
                 this.OrganizationName?.Equals(other.OrganizationName) == true) &&
                (this.ServicePlans == null && other.ServicePlans == null ||
                 this.ServicePlans?.Equals(other.ServicePlans) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountName = {this.AccountName ?? "null"}");
            toStringOutput.Add($"AccountNumber = {this.AccountNumber ?? "null"}");
            toStringOutput.Add($"Carriers = {(this.Carriers == null ? "null" : $"[{string.Join(", ", this.Carriers)} ]")}");
            toStringOutput.Add($"Features = {(this.Features == null ? "null" : $"[{string.Join(", ", this.Features)} ]")}");
            toStringOutput.Add($"IpPools = {(this.IpPools == null ? "null" : $"[{string.Join(", ", this.IpPools)} ]")}");
            toStringOutput.Add($"IsProvisioningAllowed = {(this.IsProvisioningAllowed == null ? "null" : this.IsProvisioningAllowed.ToString())}");
            toStringOutput.Add($"OrganizationName = {this.OrganizationName ?? "null"}");
            toStringOutput.Add($"ServicePlans = {(this.ServicePlans == null ? "null" : $"[{string.Join(", ", this.ServicePlans)} ]")}");
        }
    }
}