// <copyright file="Grass.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// Grass.
    /// </summary>
    public class Grass
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Grass"/> class.
        /// </summary>
        public Grass()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Grass"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        public Grass(
            Models.Type9Enum? type = null)
        {
            this.Type = type;
        }

        /// <summary>
        /// Indicates the surface of the roadway is grass with low speed limit.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Type9Enum? Type { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Grass : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Grass other &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {(this.Type == null ? "null" : this.Type.ToString())}");
        }
    }
}