// <copyright file="LogInRequest.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// LogInRequest.
    /// </summary>
    public class LogInRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LogInRequest"/> class.
        /// </summary>
        public LogInRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LogInRequest"/> class.
        /// </summary>
        /// <param name="username">username.</param>
        /// <param name="password">password.</param>
        public LogInRequest(
            string username,
            string password)
        {
            this.Username = username;
            this.Password = password;
        }

        /// <summary>
        /// The username for authentication.
        /// </summary>
        [JsonProperty("username")]
        public string Username { get; set; }

        /// <summary>
        /// The password for authentication.
        /// </summary>
        [JsonProperty("password")]
        public string Password { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"LogInRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is LogInRequest other &&
                (this.Username == null && other.Username == null ||
                 this.Username?.Equals(other.Username) == true) &&
                (this.Password == null && other.Password == null ||
                 this.Password?.Equals(other.Password) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Username = {this.Username ?? "null"}");
            toStringOutput.Add($"Password = {this.Password ?? "null"}");
        }
    }
}