// <copyright file="M5gBideviceIdarray.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;
using Verizon.Standard.Models.Containers;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// M5gBideviceIdarray.
    /// </summary>
    public class M5gBideviceIdarray
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="M5gBideviceIdarray"/> class.
        /// </summary>
        public M5gBideviceIdarray()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="M5gBideviceIdarray"/> class.
        /// </summary>
        /// <param name="deviceId">deviceId.</param>
        public M5gBideviceIdarray(
            List<M5gBideviceIdarrayDeviceId> deviceId = null)
        {
            this.DeviceId = deviceId;
        }

        /// <summary>
        /// Gets or sets DeviceId.
        /// </summary>
        [JsonProperty("deviceId", NullValueHandling = NullValueHandling.Ignore)]
        public List<M5gBideviceIdarrayDeviceId> DeviceId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"M5gBideviceIdarray : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is M5gBideviceIdarray other &&
                (this.DeviceId == null && other.DeviceId == null ||
                 this.DeviceId?.Equals(other.DeviceId) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DeviceId = {(this.DeviceId == null ? "null" : this.DeviceId.ToString())}");
        }
    }
}