// <copyright file="Message1.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;
using Verizon.Standard.Models.Containers;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// Message1.
    /// </summary>
    public class Message1
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Message1"/> class.
        /// </summary>
        public Message1()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Message1"/> class.
        /// </summary>
        /// <param name="isPrivate">isPrivate.</param>
        /// <param name="roadUserType">roadUserType.</param>
        /// <param name="triggerConditions">triggerConditions.</param>
        /// <param name="saeAlert">saeAlert.</param>
        /// <param name="limits">limits.</param>
        /// <param name="distributionType">distributionType.</param>
        /// <param name="distributionSchedule">distributionSchedule.</param>
        public Message1(
            bool isPrivate,
            List<Models.RoadUserTypesEnum> roadUserType,
            List<Models.TriggerConditionEnum> triggerConditions,
            Models.SaeAlert saeAlert,
            List<Limits> limits = null,
            List<Models.DistributionTypesEnum> distributionType = null,
            Models.DistributionSchedule distributionSchedule = null)
        {
            this.IsPrivate = isPrivate;
            this.RoadUserType = roadUserType;
            this.TriggerConditions = triggerConditions;
            this.Limits = limits;
            this.DistributionType = distributionType;
            this.DistributionSchedule = distributionSchedule;
            this.SaeAlert = saeAlert;
        }

        /// <summary>
        /// Defines whether the message is private or public.
        /// Private messages are published under the Vendor ID defined in the configuration and only visible to devices of selected vendors.
        /// Public messages are published under the Public vendor and are visible to all the users.
        /// </summary>
        [JsonProperty("isPrivate")]
        [JsonRequired]
        public bool IsPrivate { get; set; }

        /// <summary>
        /// Type of the Road User.
        /// </summary>
        [JsonProperty("roadUserType")]
        [JsonRequired]
        public List<Models.RoadUserTypesEnum> RoadUserType { get; set; }

        /// <summary>
        /// Trigger conditions that define on which road user action the message will be sent. If multiple Trigger Conditions are defined any of them will trigger the message.
        /// </summary>
        [JsonProperty("triggerConditions")]
        [JsonRequired]
        public List<Models.TriggerConditionEnum> TriggerConditions { get; set; }

        /// <summary>
        /// List of limitations. These limitations can be used for making the trigger condition more precise by defining speed and motion direction requirements to be met before the messages are sent out.
        /// </summary>
        [JsonProperty("limits", NullValueHandling = NullValueHandling.Ignore)]
        public List<Limits> Limits { get; set; }

        /// <summary>
        /// Type of the distribution.
        /// </summary>
        [JsonProperty("distributionType", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.DistributionTypesEnum> DistributionType { get; set; }

        /// <summary>
        /// The distribution schedule parameters for broadcast messages.
        /// </summary>
        [JsonProperty("distributionSchedule", NullValueHandling = NullValueHandling.Ignore)]
        public Models.DistributionSchedule DistributionSchedule { get; set; }

        /// <summary>
        /// Gets or sets SaeAlert.
        /// </summary>
        [JsonProperty("saeAlert")]
        [JsonRequired]
        public Models.SaeAlert SaeAlert { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Message1 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Message1 other &&
                (this.IsPrivate.Equals(other.IsPrivate)) &&
                (this.RoadUserType == null && other.RoadUserType == null ||
                 this.RoadUserType?.Equals(other.RoadUserType) == true) &&
                (this.TriggerConditions == null && other.TriggerConditions == null ||
                 this.TriggerConditions?.Equals(other.TriggerConditions) == true) &&
                (this.Limits == null && other.Limits == null ||
                 this.Limits?.Equals(other.Limits) == true) &&
                (this.DistributionType == null && other.DistributionType == null ||
                 this.DistributionType?.Equals(other.DistributionType) == true) &&
                (this.DistributionSchedule == null && other.DistributionSchedule == null ||
                 this.DistributionSchedule?.Equals(other.DistributionSchedule) == true) &&
                (this.SaeAlert == null && other.SaeAlert == null ||
                 this.SaeAlert?.Equals(other.SaeAlert) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"IsPrivate = {this.IsPrivate}");
            toStringOutput.Add($"RoadUserType = {(this.RoadUserType == null ? "null" : $"[{string.Join(", ", this.RoadUserType)} ]")}");
            toStringOutput.Add($"TriggerConditions = {(this.TriggerConditions == null ? "null" : $"[{string.Join(", ", this.TriggerConditions)} ]")}");
            toStringOutput.Add($"Limits = {(this.Limits == null ? "null" : this.Limits.ToString())}");
            toStringOutput.Add($"DistributionType = {(this.DistributionType == null ? "null" : $"[{string.Join(", ", this.DistributionType)} ]")}");
            toStringOutput.Add($"DistributionSchedule = {(this.DistributionSchedule == null ? "null" : this.DistributionSchedule.ToString())}");
            toStringOutput.Add($"SaeAlert = {(this.SaeAlert == null ? "null" : this.SaeAlert.ToString())}");
        }
    }
}