// <copyright file="MsgId1.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// MsgId1.
    /// </summary>
    public class MsgId1
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MsgId1"/> class.
        /// </summary>
        public MsgId1()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MsgId1"/> class.
        /// </summary>
        /// <param name="roadSignID">roadSignID.</param>
        public MsgId1(
            Models.RoadSignID roadSignID)
        {
            this.RoadSignID = roadSignID;
        }

        /// <summary>
        /// It provide a precise location of one or more roadside signs.
        /// </summary>
        [JsonProperty("roadSignID")]
        [JsonRequired]
        public Models.RoadSignID RoadSignID { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"MsgId1 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is MsgId1 other &&
                (this.RoadSignID == null && other.RoadSignID == null ||
                 this.RoadSignID?.Equals(other.RoadSignID) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"RoadSignID = {(this.RoadSignID == null ? "null" : this.RoadSignID.ToString())}");
        }
    }
}