// <copyright file="Notify.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;
using Verizon.Standard.Models.Containers;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// Notify.
    /// </summary>
    public class Notify
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Notify"/> class.
        /// </summary>
        public Notify()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Notify"/> class.
        /// </summary>
        /// <param name="alertType">alertType.</param>
        /// <param name="threshold">threshold.</param>
        public Notify(
            string alertType = null,
            List<NotifyThreshold> threshold = null)
        {
            this.AlertType = alertType;
            this.Threshold = threshold;
        }

        /// <summary>
        /// Gets or sets AlertType.
        /// </summary>
        [JsonProperty("alertType", NullValueHandling = NullValueHandling.Ignore)]
        public string AlertType { get; set; }

        /// <summary>
        /// Gets or sets Threshold.
        /// </summary>
        [JsonProperty("threshold", NullValueHandling = NullValueHandling.Ignore)]
        public List<NotifyThreshold> Threshold { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Notify : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Notify other &&
                (this.AlertType == null && other.AlertType == null ||
                 this.AlertType?.Equals(other.AlertType) == true) &&
                (this.Threshold == null && other.Threshold == null ||
                 this.Threshold?.Equals(other.Threshold) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AlertType = {this.AlertType ?? "null"}");
            toStringOutput.Add($"Threshold = {(this.Threshold == null ? "null" : this.Threshold.ToString())}");
        }
    }
}