// <copyright file="Offboarding.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// Offboarding.
    /// </summary>
    public class Offboarding
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Offboarding"/> class.
        /// </summary>
        public Offboarding()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Offboarding"/> class.
        /// </summary>
        /// <param name="sensoridentifier">sensoridentifier.</param>
        public Offboarding(
            string sensoridentifier = null)
        {
            this.Sensoridentifier = sensoridentifier;
        }

        /// <summary>
        /// the IEEE EUI64 address space used to identify a device. It is supplied by the device manufacturer
        /// </summary>
        [JsonProperty("sensoridentifier", NullValueHandling = NullValueHandling.Ignore)]
        public string Sensoridentifier { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Offboarding : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Offboarding other &&
                (this.Sensoridentifier == null && other.Sensoridentifier == null ||
                 this.Sensoridentifier?.Equals(other.Sensoridentifier) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Sensoridentifier = {this.Sensoridentifier ?? "null"}");
        }
    }
}