// <copyright file="PayAsYouGoFilterCriteria.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// PayAsYouGoFilterCriteria.
    /// </summary>
    public class PayAsYouGoFilterCriteria
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayAsYouGoFilterCriteria"/> class.
        /// </summary>
        public PayAsYouGoFilterCriteria()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PayAsYouGoFilterCriteria"/> class.
        /// </summary>
        /// <param name="filterCriteria">filterCriteria.</param>
        public PayAsYouGoFilterCriteria(
            Models.PayAsYouGoFilterCriteria1 filterCriteria = null)
        {
            this.FilterCriteria = filterCriteria;
        }

        /// <summary>
        /// Gets or sets FilterCriteria.
        /// </summary>
        [JsonProperty("filterCriteria", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PayAsYouGoFilterCriteria1 FilterCriteria { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PayAsYouGoFilterCriteria : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PayAsYouGoFilterCriteria other &&
                (this.FilterCriteria == null && other.FilterCriteria == null ||
                 this.FilterCriteria?.Equals(other.FilterCriteria) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"FilterCriteria = {(this.FilterCriteria == null ? "null" : this.FilterCriteria.ToString())}");
        }
    }
}