// <copyright file="PricePlanTrigger.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;
using Verizon.Standard.Models.Containers;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// PricePlanTrigger.
    /// </summary>
    public class PricePlanTrigger
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PricePlanTrigger"/> class.
        /// </summary>
        public PricePlanTrigger()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PricePlanTrigger"/> class.
        /// </summary>
        /// <param name="standAlone">standAlone.</param>
        /// <param name="condition">condition.</param>
        /// <param name="action">action.</param>
        public PricePlanTrigger(
            Models.FiltercriteriaObjectCall standAlone = null,
            PricePlanTriggerCondition condition = null,
            Models.Actionobject action = null)
        {
            this.StandAlone = standAlone;
            this.Condition = condition;
            this.Action = action;
        }

        /// <summary>
        /// Gets or sets StandAlone.
        /// </summary>
        [JsonProperty("standAlone", NullValueHandling = NullValueHandling.Ignore)]
        public Models.FiltercriteriaObjectCall StandAlone { get; set; }

        /// <summary>
        /// Gets or sets Condition.
        /// </summary>
        [JsonProperty("condition", NullValueHandling = NullValueHandling.Ignore)]
        public PricePlanTriggerCondition Condition { get; set; }

        /// <summary>
        /// Gets or sets Action.
        /// </summary>
        [JsonProperty("action", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Actionobject Action { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PricePlanTrigger : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PricePlanTrigger other &&
                (this.StandAlone == null && other.StandAlone == null ||
                 this.StandAlone?.Equals(other.StandAlone) == true) &&
                (this.Condition == null && other.Condition == null ||
                 this.Condition?.Equals(other.Condition) == true) &&
                (this.Action == null && other.Action == null ||
                 this.Action?.Equals(other.Action) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"StandAlone = {(this.StandAlone == null ? "null" : this.StandAlone.ToString())}");
            toStringOutput.Add($"Condition = {(this.Condition == null ? "null" : this.Condition.ToString())}");
            toStringOutput.Add($"Action = {(this.Action == null ? "null" : this.Action.ToString())}");
        }
    }
}