// <copyright file="RoadSignID.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// RoadSignID.
    /// </summary>
    public class RoadSignID
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RoadSignID"/> class.
        /// </summary>
        public RoadSignID()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RoadSignID"/> class.
        /// </summary>
        /// <param name="position">position.</param>
        /// <param name="viewAngle">viewAngle.</param>
        public RoadSignID(
            Models.Position position,
            string viewAngle)
        {
            this.Position = position;
            this.ViewAngle = viewAngle;
        }

        /// <summary>
        /// It provides a precise location in the WGS-84 coordinate system, from which short offsets may be used to create additional data using a flat earth projection centered on this location.
        /// </summary>
        [JsonProperty("position")]
        public Models.Position Position { get; set; }

        /// <summary>
        /// OctetStrings are described as hexadecimal strings, where each octet is represented by two hexadecimal characters.
        /// </summary>
        [JsonProperty("viewAngle")]
        public string ViewAngle { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RoadSignID : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RoadSignID other &&
                (this.Position == null && other.Position == null ||
                 this.Position?.Equals(other.Position) == true) &&
                (this.ViewAngle == null && other.ViewAngle == null ||
                 this.ViewAngle?.Equals(other.ViewAngle) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Position = {(this.Position == null ? "null" : this.Position.ToString())}");
            toStringOutput.Add($"ViewAngle = {this.ViewAngle ?? "null"}");
        }
    }
}