// <copyright file="SensitivityParameters.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// SensitivityParameters.
    /// </summary>
    public class SensitivityParameters
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SensitivityParameters"/> class.
        /// </summary>
        public SensitivityParameters()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SensitivityParameters"/> class.
        /// </summary>
        /// <param name="abnormalMaxValue">abnormalMaxValue.</param>
        /// <param name="enableAbnormal">enableAbnormal.</param>
        /// <param name="enableVeryAbnormal">enableVeryAbnormal.</param>
        /// <param name="veryAbnormalMaxValue">veryAbnormalMaxValue.</param>
        public SensitivityParameters(
            double? abnormalMaxValue = null,
            bool? enableAbnormal = null,
            bool? enableVeryAbnormal = null,
            double? veryAbnormalMaxValue = null)
        {
            this.AbnormalMaxValue = abnormalMaxValue;
            this.EnableAbnormal = enableAbnormal;
            this.EnableVeryAbnormal = enableVeryAbnormal;
            this.VeryAbnormalMaxValue = veryAbnormalMaxValue;
        }

        /// <summary>
        /// The maximum value of the threshold in the units being measured.
        /// </summary>
        [JsonProperty("abnormalMaxValue", NullValueHandling = NullValueHandling.Ignore)]
        public double? AbnormalMaxValue { get; set; }

        /// <summary>
        /// If abnormal values are being monitored.<br />true - Monitor for abnormal values<br />false - Do not monitor for abnormal values.
        /// </summary>
        [JsonProperty("enableAbnormal", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EnableAbnormal { get; set; }

        /// <summary>
        /// If very abnormal values are being monitored.<br />true - Monitor for very abnormal values<br />false - Do not monitor for very abnormal values.
        /// </summary>
        [JsonProperty("enableVeryAbnormal", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EnableVeryAbnormal { get; set; }

        /// <summary>
        /// The maximum value of the threshold in the units being measured.
        /// </summary>
        [JsonProperty("veryAbnormalMaxValue", NullValueHandling = NullValueHandling.Ignore)]
        public double? VeryAbnormalMaxValue { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SensitivityParameters : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SensitivityParameters other &&
                (this.AbnormalMaxValue == null && other.AbnormalMaxValue == null ||
                 this.AbnormalMaxValue?.Equals(other.AbnormalMaxValue) == true) &&
                (this.EnableAbnormal == null && other.EnableAbnormal == null ||
                 this.EnableAbnormal?.Equals(other.EnableAbnormal) == true) &&
                (this.EnableVeryAbnormal == null && other.EnableVeryAbnormal == null ||
                 this.EnableVeryAbnormal?.Equals(other.EnableVeryAbnormal) == true) &&
                (this.VeryAbnormalMaxValue == null && other.VeryAbnormalMaxValue == null ||
                 this.VeryAbnormalMaxValue?.Equals(other.VeryAbnormalMaxValue) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AbnormalMaxValue = {(this.AbnormalMaxValue == null ? "null" : this.AbnormalMaxValue.ToString())}");
            toStringOutput.Add($"EnableAbnormal = {(this.EnableAbnormal == null ? "null" : this.EnableAbnormal.ToString())}");
            toStringOutput.Add($"EnableVeryAbnormal = {(this.EnableVeryAbnormal == null ? "null" : this.EnableVeryAbnormal.ToString())}");
            toStringOutput.Add($"VeryAbnormalMaxValue = {(this.VeryAbnormalMaxValue == null ? "null" : this.VeryAbnormalMaxValue.ToString())}");
        }
    }
}