// <copyright file="ServiceNameEnum.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// ServiceNameEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ServiceNameEnum
    {
        /// <summary>
        /// Location.
        /// </summary>
        [EnumMember(Value = "Location")]
        Location,

        /// <summary>
        /// Fota.
        /// </summary>
        [EnumMember(Value = "fota")]
        Fota
    }
}