// <copyright file="SessionReport.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// SessionReport.
    /// </summary>
    public class SessionReport
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SessionReport"/> class.
        /// </summary>
        public SessionReport()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SessionReport"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="txid">txid.</param>
        /// <param name="sessions">sessions.</param>
        public SessionReport(
            string id,
            string txid,
            List<Models.DailyUsageItem> sessions = null)
        {
            this.Id = id;
            this.Txid = txid;
            this.Sessions = sessions;
        }

        /// <summary>
        /// The 10-digit ID of the device.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// A unique string (UUID) that associates the request with the location report information that is sent in asynchronous callback message.ThingSpace will send a separate callback message for each device that was in the request. All of the callback messages will have a txid.
        /// </summary>
        [JsonProperty("txid")]
        public string Txid { get; set; }

        /// <summary>
        /// An object containing the start and end time of the session with the amount of data transferred.
        /// </summary>
        [JsonProperty("sessions", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.DailyUsageItem> Sessions { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SessionReport : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SessionReport other &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.Txid == null && other.Txid == null ||
                 this.Txid?.Equals(other.Txid) == true) &&
                (this.Sessions == null && other.Sessions == null ||
                 this.Sessions?.Equals(other.Sessions) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"Txid = {this.Txid ?? "null"}");
            toStringOutput.Add($"Sessions = {(this.Sessions == null ? "null" : $"[{string.Join(", ", this.Sessions)} ]")}");
        }
    }
}