// <copyright file="SessionReportRequest.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// SessionReportRequest.
    /// </summary>
    public class SessionReportRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SessionReportRequest"/> class.
        /// </summary>
        public SessionReportRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SessionReportRequest"/> class.
        /// </summary>
        /// <param name="accountNumber">accountNumber.</param>
        /// <param name="imei">imei.</param>
        /// <param name="startDate">startDate.</param>
        /// <param name="endDate">endDate.</param>
        /// <param name="durationLow">durationLow.</param>
        /// <param name="durationHigh">durationHigh.</param>
        public SessionReportRequest(
            string accountNumber,
            string imei,
            string startDate = null,
            string endDate = null,
            int? durationLow = null,
            int? durationHigh = null)
        {
            this.AccountNumber = accountNumber;
            this.Imei = imei;
            this.StartDate = startDate;
            this.EndDate = endDate;
            this.DurationLow = durationLow;
            this.DurationHigh = durationHigh;
        }

        /// <summary>
        /// The numeric ID of the account and must include leading zeroes. This value is indentical to `accountName`.
        /// </summary>
        [JsonProperty("accountNumber")]
        public string AccountNumber { get; set; }

        /// <summary>
        /// The International Mobile Equipment Identifier of the device.
        /// </summary>
        [JsonProperty("imei")]
        public string Imei { get; set; }

        /// <summary>
        /// Start date of session to include. If not specified  information will be shown from the earliest available (180 days). Can be either date in ISO 8601 format or predefined constants.
        /// </summary>
        [JsonProperty("startDate", NullValueHandling = NullValueHandling.Ignore)]
        public string StartDate { get; set; }

        /// <summary>
        /// End date of session to include. If not specified  information will be shown to the latest available. Can be either date in ISO 8601 format or predefined constants.
        /// </summary>
        [JsonProperty("endDate", NullValueHandling = NullValueHandling.Ignore)]
        public string EndDate { get; set; }

        /// <summary>
        /// Optional filter — minimum session duration
        /// </summary>
        [JsonProperty("durationLow", NullValueHandling = NullValueHandling.Ignore)]
        public int? DurationLow { get; set; }

        /// <summary>
        /// Optional filter — maximum session duration
        /// </summary>
        [JsonProperty("durationHigh", NullValueHandling = NullValueHandling.Ignore)]
        public int? DurationHigh { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SessionReportRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SessionReportRequest other &&
                (this.AccountNumber == null && other.AccountNumber == null ||
                 this.AccountNumber?.Equals(other.AccountNumber) == true) &&
                (this.Imei == null && other.Imei == null ||
                 this.Imei?.Equals(other.Imei) == true) &&
                (this.StartDate == null && other.StartDate == null ||
                 this.StartDate?.Equals(other.StartDate) == true) &&
                (this.EndDate == null && other.EndDate == null ||
                 this.EndDate?.Equals(other.EndDate) == true) &&
                (this.DurationLow == null && other.DurationLow == null ||
                 this.DurationLow?.Equals(other.DurationLow) == true) &&
                (this.DurationHigh == null && other.DurationHigh == null ||
                 this.DurationHigh?.Equals(other.DurationHigh) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountNumber = {this.AccountNumber ?? "null"}");
            toStringOutput.Add($"Imei = {this.Imei ?? "null"}");
            toStringOutput.Add($"StartDate = {this.StartDate ?? "null"}");
            toStringOutput.Add($"EndDate = {this.EndDate ?? "null"}");
            toStringOutput.Add($"DurationLow = {(this.DurationLow == null ? "null" : this.DurationLow.ToString())}");
            toStringOutput.Add($"DurationHigh = {(this.DurationHigh == null ? "null" : this.DurationHigh.ToString())}");
        }
    }
}