// <copyright file="TriggerValueResponse2.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;
using Verizon.Standard.Models.Containers;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// TriggerValueResponse2.
    /// </summary>
    public class TriggerValueResponse2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TriggerValueResponse2"/> class.
        /// </summary>
        public TriggerValueResponse2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TriggerValueResponse2"/> class.
        /// </summary>
        /// <param name="triggers">triggers.</param>
        public TriggerValueResponse2(
            List<TriggervalueChunk2> triggers = null)
        {
            this.Triggers = triggers;
        }

        /// <summary>
        /// Gets or sets Triggers.
        /// </summary>
        [JsonProperty("triggers", NullValueHandling = NullValueHandling.Ignore)]
        public List<TriggervalueChunk2> Triggers { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TriggerValueResponse2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TriggerValueResponse2 other &&
                (this.Triggers == null && other.Triggers == null ||
                 this.Triggers?.Equals(other.Triggers) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Triggers = {(this.Triggers == null ? "null" : this.Triggers.ToString())}");
        }
    }
}