// <copyright file="UnitEnum.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// UnitEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnitEnum
    {
        /// <summary>
        /// Minutes.
        /// </summary>
        [EnumMember(Value = "minutes")]
        Minutes,

        /// <summary>
        /// Hours.
        /// </summary>
        [EnumMember(Value = "hours")]
        Hours
    }
}