// <copyright file="UpgradeStatusEnum.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// UpgradeStatusEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UpgradeStatusEnum
    {
        /// <summary>
        /// RequestPending.
        /// </summary>
        [EnumMember(Value = "RequestPending")]
        RequestPending,

        /// <summary>
        /// Queued.
        /// </summary>
        [EnumMember(Value = "Queued")]
        Queued,

        /// <summary>
        /// RequestFailed.
        /// </summary>
        [EnumMember(Value = "RequestFailed")]
        RequestFailed,

        /// <summary>
        /// InProgress.
        /// </summary>
        [EnumMember(Value = "InProgress")]
        InProgress,

        /// <summary>
        /// Finished.
        /// </summary>
        [EnumMember(Value = "Finished")]
        Finished,

        /// <summary>
        /// UpgradeFailed.
        /// </summary>
        [EnumMember(Value = "UpgradeFailed")]
        UpgradeFailed
    }
}