// <copyright file="V1LicensesAssignedRemovedRequest.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// V1LicensesAssignedRemovedRequest.
    /// </summary>
    public class V1LicensesAssignedRemovedRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1LicensesAssignedRemovedRequest"/> class.
        /// </summary>
        public V1LicensesAssignedRemovedRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="V1LicensesAssignedRemovedRequest"/> class.
        /// </summary>
        /// <param name="deviceList">deviceList.</param>
        public V1LicensesAssignedRemovedRequest(
            List<string> deviceList)
        {
            this.DeviceList = deviceList;
        }

        /// <summary>
        /// The IMEIs of the devices.
        /// </summary>
        [JsonProperty("deviceList")]
        public List<string> DeviceList { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"V1LicensesAssignedRemovedRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is V1LicensesAssignedRemovedRequest other &&
                (this.DeviceList == null && other.DeviceList == null ||
                 this.DeviceList?.Equals(other.DeviceList) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DeviceList = {(this.DeviceList == null ? "null" : $"[{string.Join(", ", this.DeviceList)} ]")}");
        }
    }
}