// <copyright file="V3LicenseDevice.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Verizon.Standard.Models
{
    /// <summary>
    /// V3LicenseDevice.
    /// </summary>
    public class V3LicenseDevice
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V3LicenseDevice"/> class.
        /// </summary>
        public V3LicenseDevice()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="V3LicenseDevice"/> class.
        /// </summary>
        /// <param name="deviceId">deviceId.</param>
        /// <param name="assignmentTime">assignmentTime.</param>
        public V3LicenseDevice(
            string deviceId,
            string assignmentTime = null)
        {
            this.DeviceId = deviceId;
            this.AssignmentTime = assignmentTime;
        }

        /// <summary>
        /// Device IMEI.
        /// </summary>
        [JsonProperty("deviceId")]
        public string DeviceId { get; set; }

        /// <summary>
        /// License assignment time.
        /// </summary>
        [JsonProperty("assignmentTime", NullValueHandling = NullValueHandling.Ignore)]
        public string AssignmentTime { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"V3LicenseDevice : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is V3LicenseDevice other &&
                (this.DeviceId == null && other.DeviceId == null ||
                 this.DeviceId?.Equals(other.DeviceId) == true) &&
                (this.AssignmentTime == null && other.AssignmentTime == null ||
                 this.AssignmentTime?.Equals(other.AssignmentTime) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DeviceId = {this.DeviceId ?? "null"}");
            toStringOutput.Add($"AssignmentTime = {this.AssignmentTime ?? "null"}");
        }
    }
}