// <copyright file="Server.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>

namespace Verizon.Standard
{
    /// <summary>
    /// Available servers.
    /// </summary>
    public enum Server
    {
        /// <summary>
        /// HyperPreciseCredentials.
        /// </summary>
        HyperPreciseCredentials,

        /// <summary>
        /// IMPServer.
        /// </summary>
        IMPServer,

        /// <summary>
        /// Thingspace.
        /// </summary>
        Thingspace,

        /// <summary>
        /// OauthServer.
        /// </summary>
        OauthServer,

        /// <summary>
        /// M2m.
        /// </summary>
        M2m,

        /// <summary>
        /// DeviceLocation.
        /// </summary>
        DeviceLocation,

        /// <summary>
        /// SubscriptionServer.
        /// </summary>
        SubscriptionServer,

        /// <summary>
        /// SoftwareManagementV1.
        /// </summary>
        SoftwareManagementV1,

        /// <summary>
        /// SoftwareManagementV2.
        /// </summary>
        SoftwareManagementV2,

        /// <summary>
        /// SoftwareManagementV3.
        /// </summary>
        SoftwareManagementV3,

        /// <summary>
        /// DeviceDiagnostics.
        /// </summary>
        DeviceDiagnostics,

        /// <summary>
        /// CloudConnector.
        /// </summary>
        CloudConnector,

        /// <summary>
        /// HyperPreciseLocation.
        /// </summary>
        HyperPreciseLocation,

        /// <summary>
        /// Services.
        /// </summary>
        Services,

        /// <summary>
        /// QualityOfService.
        /// </summary>
        QualityOfService,
    }
}
