// <copyright file="VerizonClient.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Authentication;
using APIMatic.Core.Utilities;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using Verizon.Standard.Authentication;
using Verizon.Standard.Controllers;
using Verizon.Standard.Http.Client;

namespace Verizon.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Controller and
    /// holds the configuration of the SDK.
    /// </summary>
    public sealed class VerizonClient : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.Production, new Dictionary<Enum, string>
                {
                    { Server.HyperPreciseCredentials, "https://thingspace.verizon.com/api/auth/v1" },
                    { Server.IMPServer, "https://imp.thingspace.verizon.com" },
                    { Server.Thingspace, "https://thingspace.verizon.com/api" },
                    { Server.OauthServer, "https://thingspace.verizon.com/api/ts/v1" },
                    { Server.M2m, "https://thingspace.verizon.com/api/m2m" },
                    { Server.DeviceLocation, "https://thingspace.verizon.com/api/loc/v1" },
                    { Server.SubscriptionServer, "https://thingspace.verizon.com/api/subsc/v1" },
                    { Server.SoftwareManagementV1, "https://thingspace.verizon.com/api/fota/v1" },
                    { Server.SoftwareManagementV2, "https://thingspace.verizon.com/api/fota/v2" },
                    { Server.SoftwareManagementV3, "https://thingspace.verizon.com/api/fota/v3" },
                    { Server.DeviceDiagnostics, "https://thingspace.verizon.com/api/diagnostics/v1" },
                    { Server.CloudConnector, "https://thingspace.verizon.com/api/cc/v1" },
                    { Server.HyperPreciseLocation, "https://thingspace.verizon.com/api/hyper-precise/v1" },
                    { Server.Services, "https://5gedge.verizon.com/api/mec/services" },
                    { Server.QualityOfService, "https://thingspace.verizon.com/api/m2m/v1/devices" },
                }
            },
            {
                Environment.Staging, new Dictionary<Enum, string>
                {
                    { Server.HyperPreciseCredentials, "https://staging.thingspace.verizon.com/api/auth/v1" },
                    { Server.IMPServer, "https://imp-staging.thingspace.verizon.com" },
                    { Server.Thingspace, "https://staging.thingspace.verizon.com/api" },
                    { Server.OauthServer, "https://staging.thingspace.verizon.com/api/ts/v1" },
                    { Server.M2m, "https://staging.thingspace.verizon.com/api/m2m" },
                    { Server.DeviceLocation, "https://staging.thingspace.verizon.com/api/loc/v1" },
                    { Server.SubscriptionServer, "https://staging.thingspace.verizon.com/api/subsc/v1" },
                    { Server.SoftwareManagementV1, "https://staging.thingspace.verizon.com/api/fota/v1" },
                    { Server.SoftwareManagementV2, "https://staging.thingspace.verizon.com/api/fota/v2" },
                    { Server.SoftwareManagementV3, "https://staging.thingspace.verizon.com/api/fota/v3" },
                    { Server.DeviceDiagnostics, "https://staging.thingspace.verizon.com/api/diagnostics/v1" },
                    { Server.CloudConnector, "https://staging.thingspace.verizon.com/api/cc/v1" },
                    { Server.HyperPreciseLocation, "https://staging.thingspace.verizon.com/api/hyper-precise/v1" },
                    { Server.Services, "https://staging.5gedge.verizon.com/api/mec/services" },
                    { Server.QualityOfService, "https://staging.thingspace.verizon.com/api/m2m/v1/devices" },
                }
            },
            {
                Environment.Dev, new Dictionary<Enum, string>
                {
                    { Server.HyperPreciseCredentials, "https://staging.thingspace.verizon.com/api/auth/v1" },
                    { Server.IMPServer, "https://devmanagement-staging.imp.thingspace.verizon.com" },
                    { Server.Thingspace, "https://devmanagement-staging.thingspace.verizon.com/api" },
                    { Server.OauthServer, "https://devmanagement-staging.thingspace.verizon.com:80/ts/v1" },
                    { Server.M2m, "https://devmanagement-staging.thingspace.verizon.com:80/m2m" },
                    { Server.DeviceLocation, "https://devmanagement-staging.thingspace.verizon.com:80/loc/v1" },
                    { Server.SubscriptionServer, "https://devmanagement-staging.thingspace.verizon.com:80/subsc/v1" },
                    { Server.SoftwareManagementV1, "https://devmanagement-staging.thingspace.verizon.com:80/fota/v1" },
                    { Server.SoftwareManagementV2, "https://devmanagement-staging.thingspace.verizon.com:80/fota/v2" },
                    { Server.SoftwareManagementV3, "https://devmanagement-staging.thingspace.verizon.com:80/fota/v3" },
                    { Server.DeviceDiagnostics, "https://devmanagement-staging.thingspace.verizon.com:80/diagnostics/v1" },
                    { Server.CloudConnector, "https://devmanagement-staging.thingspace.verizon.com:80/cc/v1" },
                    { Server.HyperPreciseLocation, "https://devmanagement-staging.thingspace.verizon.com:80/hyper-precise/v1" },
                    { Server.Services, "https://devmanagement-staging.5gedge.verizon.com:80/mec/services" },
                    { Server.QualityOfService, "https://devmanagement-staging.thingspace.verizon.com/api/m2m/v1/devices" },
                }
            },
            {
                Environment.Qa, new Dictionary<Enum, string>
                {
                    { Server.HyperPreciseCredentials, "https://thingspace.verizon.com/api/auth/v1" },
                    { Server.IMPServer, "https://tsd-nginx-qa-us-east-1.imp.thingspace.verizon.com" },
                    { Server.Thingspace, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api" },
                    { Server.OauthServer, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api/ts/v1" },
                    { Server.M2m, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api/m2m" },
                    { Server.DeviceLocation, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api/loc/v1" },
                    { Server.SubscriptionServer, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api/subsc/v1" },
                    { Server.SoftwareManagementV1, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api/fota/v1" },
                    { Server.SoftwareManagementV2, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api/fota/v2" },
                    { Server.SoftwareManagementV3, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api/fota/v3" },
                    { Server.DeviceDiagnostics, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api/diagnostics/v1" },
                    { Server.CloudConnector, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api/cc/v1" },
                    { Server.HyperPreciseLocation, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api/hyper-precise/v1" },
                    { Server.Services, "https://tsd-nginx-qa-us-east-1.5gedge.verizon.com/api/mec/services" },
                    { Server.QualityOfService, "https://tsd-nginx-qa-us-east-1.thingspace.verizon.com/api/m2m/v1/devices" },
                }
            },
            {
                Environment.MockServerForLimitedAvailabilitySeeQuickStart, new Dictionary<Enum, string>
                {
                    { Server.HyperPreciseCredentials, "https://staging.thingspace.verizon.com/api/auth/v1" },
                    { Server.IMPServer, "https://mock-staging.thingspace.verizon.com" },
                    { Server.Thingspace, "https://mock-staging.thingspace.verizon.com/api" },
                    { Server.OauthServer, "https://mock-staging.thingspace.verizon.com/api/ts/v1" },
                    { Server.M2m, "https://mock-staging.thingspace.verizon.com/api/m2m" },
                    { Server.DeviceLocation, "https://mock-staging.thingspace.verizon.com/api/loc/v1" },
                    { Server.SubscriptionServer, "https://mock-staging.thingspace.verizon.com/api/subsc/v1" },
                    { Server.SoftwareManagementV1, "https://mock-staging.thingspace.verizon.com/api/fota/v1" },
                    { Server.SoftwareManagementV2, "https://mock-staging.thingspace.verizon.com/api/fota/v2" },
                    { Server.SoftwareManagementV3, "https://mock-staging.thingspace.verizon.com/api/fota/v3" },
                    { Server.DeviceDiagnostics, "https://mock-staging.thingspace.verizon.com/api/diagnostics/v1" },
                    { Server.CloudConnector, "https://mock-staging.thingspace.verizon.com/api/cc/v1" },
                    { Server.HyperPreciseLocation, "https://mock-staging.thingspace.verizon.com/api/hyper-precise/v1" },
                    { Server.Services, "https://mock-staging.thingspace.verizon.com/api/mec/services" },
                    { Server.QualityOfService, "https://mock-staging.thingspace.verizon.com/api/m2m/v1/devices" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private const string userAgent = "APIMATIC 3.0";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<AccountServiceController> accountServiceController;
        private readonly Lazy<IntelligenceServiceController> intelligenceServiceController;
        private readonly Lazy<DeviceManagementController> deviceManagement;
        private readonly Lazy<AccountsController> accounts;
        private readonly Lazy<DeviceGroupsController> deviceGroups;
        private readonly Lazy<SMSController> sMS;
        private readonly Lazy<SessionManagementController> sessionManagement;
        private readonly Lazy<ConnectivityCallbacksController> connectivityCallbacks;
        private readonly Lazy<AccountRequestsController> accountRequests;
        private readonly Lazy<ServicePlansController> servicePlans;
        private readonly Lazy<DeviceDiagnosticsController> deviceDiagnostics;
        private readonly Lazy<DeviceMonitoringController> deviceMonitoring;
        private readonly Lazy<DeviceProfileManagementController> deviceProfileManagement;
        private readonly Lazy<EUICCDeviceProfileManagementController> eUICCDeviceProfileManagement;
        private readonly Lazy<DevicesLocationsController> devicesLocations;
        private readonly Lazy<ExclusionsController> exclusions;
        private readonly Lazy<DevicesLocationSubscriptionsController> devicesLocationSubscriptions;
        private readonly Lazy<DeviceLocationCallbacksController> deviceLocationCallbacks;
        private readonly Lazy<UsageTriggerManagementController> usageTriggerManagement;
        private readonly Lazy<BillingController> billing;
        private readonly Lazy<SoftwareManagementSubscriptionsV1Controller> softwareManagementSubscriptionsV1;
        private readonly Lazy<SoftwareManagementLicensesV1Controller> softwareManagementLicensesV1;
        private readonly Lazy<FirmwareV1Controller> firmwareV1;
        private readonly Lazy<SoftwareManagementCallbacksV1Controller> softwareManagementCallbacksV1;
        private readonly Lazy<SoftwareManagementReportsV1Controller> softwareManagementReportsV1;
        private readonly Lazy<SoftwareManagementSubscriptionsV2Controller> softwareManagementSubscriptionsV2;
        private readonly Lazy<SoftwareManagementLicensesV2Controller> softwareManagementLicensesV2;
        private readonly Lazy<CampaignsV2Controller> campaignsV2;
        private readonly Lazy<SoftwareManagementCallbacksV2Controller> softwareManagementCallbacksV2;
        private readonly Lazy<SoftwareManagementReportsV2Controller> softwareManagementReportsV2;
        private readonly Lazy<ClientLoggingController> clientLogging;
        private readonly Lazy<ServerLoggingController> serverLogging;
        private readonly Lazy<ConfigurationFilesController> configurationFiles;
        private readonly Lazy<SoftwareManagementSubscriptionsV3Controller> softwareManagementSubscriptionsV3;
        private readonly Lazy<SoftwareManagementLicensesV3Controller> softwareManagementLicensesV3;
        private readonly Lazy<CampaignsV3Controller> campaignsV3;
        private readonly Lazy<SoftwareManagementReportsV3Controller> softwareManagementReportsV3;
        private readonly Lazy<FirmwareV3Controller> firmwareV3;
        private readonly Lazy<AccountDevicesController> accountDevices;
        private readonly Lazy<SoftwareManagementCallbacksV3Controller> softwareManagementCallbacksV3;
        private readonly Lazy<SIMSecureForIoTLicensesController> sIMSecureForIoTLicenses;
        private readonly Lazy<AccountSubscriptionsController> accountSubscriptions;
        private readonly Lazy<DiagnosticsSubscriptionsController> diagnosticsSubscriptions;
        private readonly Lazy<DiagnosticsObservationsController> diagnosticsObservations;
        private readonly Lazy<DiagnosticsHistoryController> diagnosticsHistory;
        private readonly Lazy<DiagnosticsSettingsController> diagnosticsSettings;
        private readonly Lazy<DiagnosticsCallbacksController> diagnosticsCallbacks;
        private readonly Lazy<DiagnosticsFactoryResetController> diagnosticsFactoryReset;
        private readonly Lazy<TargetsController> targets;
        private readonly Lazy<CloudConnectorSubscriptionsController> cloudConnectorSubscriptions;
        private readonly Lazy<CloudConnectorDevicesController> cloudConnectorDevices;
        private readonly Lazy<HPLDeviceManagementController> hPLDeviceManagement;
        private readonly Lazy<DeviceServiceManagementController> deviceServiceManagement;
        private readonly Lazy<DeviceReportsController> deviceReports;
        private readonly Lazy<HyperPreciseLocationCallbacksController> hyperPreciseLocationCallbacks;
        private readonly Lazy<DeviceCredentialManagementController> deviceCredentialManagement;
        private readonly Lazy<AnomalySettingsController> anomalySettings;
        private readonly Lazy<AnomalyTriggersController> anomalyTriggers;
        private readonly Lazy<AnomalyTriggersV2Controller> anomalyTriggersV2;
        private readonly Lazy<WirelessNetworkPerformanceController> wirelessNetworkPerformance;
        private readonly Lazy<ManagingESIMProfilesController> managingESIMProfiles;
        private readonly Lazy<DeviceSMSMessagingController> deviceSMSMessaging;
        private readonly Lazy<DeviceActionsController> deviceActions;
        private readonly Lazy<ThingSpaceQualityOfServiceAPIActionsController> thingSpaceQualityOfServiceAPIActions;
        private readonly Lazy<PWNController> pWN;
        private readonly Lazy<PromotionPeriodInformationController> promotionPeriodInformation;
        private readonly Lazy<RetrieveTheTriggersController> retrieveTheTriggers;
        private readonly Lazy<UpdateTriggersController> updateTriggers;
        private readonly Lazy<SIMActionsController> sIMActions;
        private readonly Lazy<GlobalReportingController> globalReporting;
        private readonly Lazy<DeviceRoleController> deviceRoleController;
        private readonly Lazy<MapDataManagerController> mapDataManager;
        private readonly Lazy<RetrieveRatePlanListController> retrieveRatePlanList;
        private readonly Lazy<CreatePricePlanTriggersController> createPricePlanTriggers;
        private readonly Lazy<UpdatePricePlanTriggersController> updatePricePlanTriggers;
        private readonly Lazy<M5gBIDeviceActionsController> m5gBIDeviceActions;
        private readonly Lazy<SensorInsightsSensorsController> sensorInsightsSensors;
        private readonly Lazy<SensorInsightsDevicesController> sensorInsightsDevices;
        private readonly Lazy<SensorInsightsGatewaysController> sensorInsightsGateways;
        private readonly Lazy<SensorInsightsSmartAlertsController> sensorInsightsSmartAlerts;
        private readonly Lazy<SensorInsightsRulesController> sensorInsightsRules;
        private readonly Lazy<SensorInsightsHealthScoreController> sensorInsightsHealthScore;
        private readonly Lazy<SensorInsightsNotificationGroupsController> sensorInsightsNotificationGroups;
        private readonly Lazy<SensorInsightsUsersController> sensorInsightsUsers;
        private readonly Lazy<SensorInsightsDeviceProfileController> sensorInsightsDeviceProfile;
        private readonly Lazy<SensorInsightsSmartAlertMetricsController> sensorInsightsSmartAlertMetrics;
        private readonly Lazy<APIController> client;
        private readonly Lazy<OauthAuthorizationController> oauthAuthorization;

        private VerizonClient(
            Environment environment,
            ThingspaceOauthModel thingspaceOauthModel,
            VZM2mTokenModel vZM2mTokenModel,
            SessionTokenModel sessionTokenModel,
            ThingspaceOauth1Model thingspaceOauth1Model,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration)
        {
            this.Environment = environment;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            ThingspaceOauthModel = thingspaceOauthModel;
            var thingspaceOauthManager = new ThingspaceOauthManager(thingspaceOauthModel,
                () => OauthAuthorizationController);
            VZM2mTokenModel = vZM2mTokenModel;
            var vZM2mTokenManager = new VZM2mTokenManager(vZM2mTokenModel);
            SessionTokenModel = sessionTokenModel;
            var sessionTokenManager = new SessionTokenManager(sessionTokenModel);
            ThingspaceOauth1Model = thingspaceOauth1Model;
            var thingspaceOauth1Manager = new ThingspaceOauth1Manager(thingspaceOauth1Model,
                () => OauthAuthorizationController);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"thingspace_oauth", thingspaceOauthManager},
                    {"VZ-M2M-Token", vZM2mTokenManager},
                    {"sessionToken", sessionTokenManager},
                    {"thingspace_oauth1", thingspaceOauth1Manager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.Thingspace)
                .UserAgent(userAgent)
                .Build();
            ThingspaceOauthCredentials = thingspaceOauthManager;
            VZM2mTokenCredentials = vZM2mTokenManager;
            SessionTokenCredentials = sessionTokenManager;
            ThingspaceOauth1Credentials = thingspaceOauth1Manager;

            this.accountServiceController = new Lazy<AccountServiceController>(
                () => new AccountServiceController(globalConfiguration));
            this.intelligenceServiceController = new Lazy<IntelligenceServiceController>(
                () => new IntelligenceServiceController(globalConfiguration));
            this.deviceManagement = new Lazy<DeviceManagementController>(
                () => new DeviceManagementController(globalConfiguration));
            this.accounts = new Lazy<AccountsController>(
                () => new AccountsController(globalConfiguration));
            this.deviceGroups = new Lazy<DeviceGroupsController>(
                () => new DeviceGroupsController(globalConfiguration));
            this.sMS = new Lazy<SMSController>(
                () => new SMSController(globalConfiguration));
            this.sessionManagement = new Lazy<SessionManagementController>(
                () => new SessionManagementController(globalConfiguration));
            this.connectivityCallbacks = new Lazy<ConnectivityCallbacksController>(
                () => new ConnectivityCallbacksController(globalConfiguration));
            this.accountRequests = new Lazy<AccountRequestsController>(
                () => new AccountRequestsController(globalConfiguration));
            this.servicePlans = new Lazy<ServicePlansController>(
                () => new ServicePlansController(globalConfiguration));
            this.deviceDiagnostics = new Lazy<DeviceDiagnosticsController>(
                () => new DeviceDiagnosticsController(globalConfiguration));
            this.deviceMonitoring = new Lazy<DeviceMonitoringController>(
                () => new DeviceMonitoringController(globalConfiguration));
            this.deviceProfileManagement = new Lazy<DeviceProfileManagementController>(
                () => new DeviceProfileManagementController(globalConfiguration));
            this.eUICCDeviceProfileManagement = new Lazy<EUICCDeviceProfileManagementController>(
                () => new EUICCDeviceProfileManagementController(globalConfiguration));
            this.devicesLocations = new Lazy<DevicesLocationsController>(
                () => new DevicesLocationsController(globalConfiguration));
            this.exclusions = new Lazy<ExclusionsController>(
                () => new ExclusionsController(globalConfiguration));
            this.devicesLocationSubscriptions = new Lazy<DevicesLocationSubscriptionsController>(
                () => new DevicesLocationSubscriptionsController(globalConfiguration));
            this.deviceLocationCallbacks = new Lazy<DeviceLocationCallbacksController>(
                () => new DeviceLocationCallbacksController(globalConfiguration));
            this.usageTriggerManagement = new Lazy<UsageTriggerManagementController>(
                () => new UsageTriggerManagementController(globalConfiguration));
            this.billing = new Lazy<BillingController>(
                () => new BillingController(globalConfiguration));
            this.softwareManagementSubscriptionsV1 = new Lazy<SoftwareManagementSubscriptionsV1Controller>(
                () => new SoftwareManagementSubscriptionsV1Controller(globalConfiguration));
            this.softwareManagementLicensesV1 = new Lazy<SoftwareManagementLicensesV1Controller>(
                () => new SoftwareManagementLicensesV1Controller(globalConfiguration));
            this.firmwareV1 = new Lazy<FirmwareV1Controller>(
                () => new FirmwareV1Controller(globalConfiguration));
            this.softwareManagementCallbacksV1 = new Lazy<SoftwareManagementCallbacksV1Controller>(
                () => new SoftwareManagementCallbacksV1Controller(globalConfiguration));
            this.softwareManagementReportsV1 = new Lazy<SoftwareManagementReportsV1Controller>(
                () => new SoftwareManagementReportsV1Controller(globalConfiguration));
            this.softwareManagementSubscriptionsV2 = new Lazy<SoftwareManagementSubscriptionsV2Controller>(
                () => new SoftwareManagementSubscriptionsV2Controller(globalConfiguration));
            this.softwareManagementLicensesV2 = new Lazy<SoftwareManagementLicensesV2Controller>(
                () => new SoftwareManagementLicensesV2Controller(globalConfiguration));
            this.campaignsV2 = new Lazy<CampaignsV2Controller>(
                () => new CampaignsV2Controller(globalConfiguration));
            this.softwareManagementCallbacksV2 = new Lazy<SoftwareManagementCallbacksV2Controller>(
                () => new SoftwareManagementCallbacksV2Controller(globalConfiguration));
            this.softwareManagementReportsV2 = new Lazy<SoftwareManagementReportsV2Controller>(
                () => new SoftwareManagementReportsV2Controller(globalConfiguration));
            this.clientLogging = new Lazy<ClientLoggingController>(
                () => new ClientLoggingController(globalConfiguration));
            this.serverLogging = new Lazy<ServerLoggingController>(
                () => new ServerLoggingController(globalConfiguration));
            this.configurationFiles = new Lazy<ConfigurationFilesController>(
                () => new ConfigurationFilesController(globalConfiguration));
            this.softwareManagementSubscriptionsV3 = new Lazy<SoftwareManagementSubscriptionsV3Controller>(
                () => new SoftwareManagementSubscriptionsV3Controller(globalConfiguration));
            this.softwareManagementLicensesV3 = new Lazy<SoftwareManagementLicensesV3Controller>(
                () => new SoftwareManagementLicensesV3Controller(globalConfiguration));
            this.campaignsV3 = new Lazy<CampaignsV3Controller>(
                () => new CampaignsV3Controller(globalConfiguration));
            this.softwareManagementReportsV3 = new Lazy<SoftwareManagementReportsV3Controller>(
                () => new SoftwareManagementReportsV3Controller(globalConfiguration));
            this.firmwareV3 = new Lazy<FirmwareV3Controller>(
                () => new FirmwareV3Controller(globalConfiguration));
            this.accountDevices = new Lazy<AccountDevicesController>(
                () => new AccountDevicesController(globalConfiguration));
            this.softwareManagementCallbacksV3 = new Lazy<SoftwareManagementCallbacksV3Controller>(
                () => new SoftwareManagementCallbacksV3Controller(globalConfiguration));
            this.sIMSecureForIoTLicenses = new Lazy<SIMSecureForIoTLicensesController>(
                () => new SIMSecureForIoTLicensesController(globalConfiguration));
            this.accountSubscriptions = new Lazy<AccountSubscriptionsController>(
                () => new AccountSubscriptionsController(globalConfiguration));
            this.diagnosticsSubscriptions = new Lazy<DiagnosticsSubscriptionsController>(
                () => new DiagnosticsSubscriptionsController(globalConfiguration));
            this.diagnosticsObservations = new Lazy<DiagnosticsObservationsController>(
                () => new DiagnosticsObservationsController(globalConfiguration));
            this.diagnosticsHistory = new Lazy<DiagnosticsHistoryController>(
                () => new DiagnosticsHistoryController(globalConfiguration));
            this.diagnosticsSettings = new Lazy<DiagnosticsSettingsController>(
                () => new DiagnosticsSettingsController(globalConfiguration));
            this.diagnosticsCallbacks = new Lazy<DiagnosticsCallbacksController>(
                () => new DiagnosticsCallbacksController(globalConfiguration));
            this.diagnosticsFactoryReset = new Lazy<DiagnosticsFactoryResetController>(
                () => new DiagnosticsFactoryResetController(globalConfiguration));
            this.targets = new Lazy<TargetsController>(
                () => new TargetsController(globalConfiguration));
            this.cloudConnectorSubscriptions = new Lazy<CloudConnectorSubscriptionsController>(
                () => new CloudConnectorSubscriptionsController(globalConfiguration));
            this.cloudConnectorDevices = new Lazy<CloudConnectorDevicesController>(
                () => new CloudConnectorDevicesController(globalConfiguration));
            this.hPLDeviceManagement = new Lazy<HPLDeviceManagementController>(
                () => new HPLDeviceManagementController(globalConfiguration));
            this.deviceServiceManagement = new Lazy<DeviceServiceManagementController>(
                () => new DeviceServiceManagementController(globalConfiguration));
            this.deviceReports = new Lazy<DeviceReportsController>(
                () => new DeviceReportsController(globalConfiguration));
            this.hyperPreciseLocationCallbacks = new Lazy<HyperPreciseLocationCallbacksController>(
                () => new HyperPreciseLocationCallbacksController(globalConfiguration));
            this.deviceCredentialManagement = new Lazy<DeviceCredentialManagementController>(
                () => new DeviceCredentialManagementController(globalConfiguration));
            this.anomalySettings = new Lazy<AnomalySettingsController>(
                () => new AnomalySettingsController(globalConfiguration));
            this.anomalyTriggers = new Lazy<AnomalyTriggersController>(
                () => new AnomalyTriggersController(globalConfiguration));
            this.anomalyTriggersV2 = new Lazy<AnomalyTriggersV2Controller>(
                () => new AnomalyTriggersV2Controller(globalConfiguration));
            this.wirelessNetworkPerformance = new Lazy<WirelessNetworkPerformanceController>(
                () => new WirelessNetworkPerformanceController(globalConfiguration));
            this.managingESIMProfiles = new Lazy<ManagingESIMProfilesController>(
                () => new ManagingESIMProfilesController(globalConfiguration));
            this.deviceSMSMessaging = new Lazy<DeviceSMSMessagingController>(
                () => new DeviceSMSMessagingController(globalConfiguration));
            this.deviceActions = new Lazy<DeviceActionsController>(
                () => new DeviceActionsController(globalConfiguration));
            this.thingSpaceQualityOfServiceAPIActions = new Lazy<ThingSpaceQualityOfServiceAPIActionsController>(
                () => new ThingSpaceQualityOfServiceAPIActionsController(globalConfiguration));
            this.pWN = new Lazy<PWNController>(
                () => new PWNController(globalConfiguration));
            this.promotionPeriodInformation = new Lazy<PromotionPeriodInformationController>(
                () => new PromotionPeriodInformationController(globalConfiguration));
            this.retrieveTheTriggers = new Lazy<RetrieveTheTriggersController>(
                () => new RetrieveTheTriggersController(globalConfiguration));
            this.updateTriggers = new Lazy<UpdateTriggersController>(
                () => new UpdateTriggersController(globalConfiguration));
            this.sIMActions = new Lazy<SIMActionsController>(
                () => new SIMActionsController(globalConfiguration));
            this.globalReporting = new Lazy<GlobalReportingController>(
                () => new GlobalReportingController(globalConfiguration));
            this.deviceRoleController = new Lazy<DeviceRoleController>(
                () => new DeviceRoleController(globalConfiguration));
            this.mapDataManager = new Lazy<MapDataManagerController>(
                () => new MapDataManagerController(globalConfiguration));
            this.retrieveRatePlanList = new Lazy<RetrieveRatePlanListController>(
                () => new RetrieveRatePlanListController(globalConfiguration));
            this.createPricePlanTriggers = new Lazy<CreatePricePlanTriggersController>(
                () => new CreatePricePlanTriggersController(globalConfiguration));
            this.updatePricePlanTriggers = new Lazy<UpdatePricePlanTriggersController>(
                () => new UpdatePricePlanTriggersController(globalConfiguration));
            this.m5gBIDeviceActions = new Lazy<M5gBIDeviceActionsController>(
                () => new M5gBIDeviceActionsController(globalConfiguration));
            this.sensorInsightsSensors = new Lazy<SensorInsightsSensorsController>(
                () => new SensorInsightsSensorsController(globalConfiguration));
            this.sensorInsightsDevices = new Lazy<SensorInsightsDevicesController>(
                () => new SensorInsightsDevicesController(globalConfiguration));
            this.sensorInsightsGateways = new Lazy<SensorInsightsGatewaysController>(
                () => new SensorInsightsGatewaysController(globalConfiguration));
            this.sensorInsightsSmartAlerts = new Lazy<SensorInsightsSmartAlertsController>(
                () => new SensorInsightsSmartAlertsController(globalConfiguration));
            this.sensorInsightsRules = new Lazy<SensorInsightsRulesController>(
                () => new SensorInsightsRulesController(globalConfiguration));
            this.sensorInsightsHealthScore = new Lazy<SensorInsightsHealthScoreController>(
                () => new SensorInsightsHealthScoreController(globalConfiguration));
            this.sensorInsightsNotificationGroups = new Lazy<SensorInsightsNotificationGroupsController>(
                () => new SensorInsightsNotificationGroupsController(globalConfiguration));
            this.sensorInsightsUsers = new Lazy<SensorInsightsUsersController>(
                () => new SensorInsightsUsersController(globalConfiguration));
            this.sensorInsightsDeviceProfile = new Lazy<SensorInsightsDeviceProfileController>(
                () => new SensorInsightsDeviceProfileController(globalConfiguration));
            this.sensorInsightsSmartAlertMetrics = new Lazy<SensorInsightsSmartAlertMetricsController>(
                () => new SensorInsightsSmartAlertMetricsController(globalConfiguration));
            this.client = new Lazy<APIController>(
                () => new APIController(globalConfiguration));
            this.oauthAuthorization = new Lazy<OauthAuthorizationController>(
                () => new OauthAuthorizationController(globalConfiguration));
        }

        /// <summary>
        /// Gets AccountServiceController controller.
        /// </summary>
        public AccountServiceController AccountServiceController => this.accountServiceController.Value;

        /// <summary>
        /// Gets IntelligenceServiceController controller.
        /// </summary>
        public IntelligenceServiceController IntelligenceServiceController => this.intelligenceServiceController.Value;

        /// <summary>
        /// Gets DeviceManagementController controller.
        /// </summary>
        public DeviceManagementController DeviceManagementController => this.deviceManagement.Value;

        /// <summary>
        /// Gets AccountsController controller.
        /// </summary>
        public AccountsController AccountsController => this.accounts.Value;

        /// <summary>
        /// Gets DeviceGroupsController controller.
        /// </summary>
        public DeviceGroupsController DeviceGroupsController => this.deviceGroups.Value;

        /// <summary>
        /// Gets SMSController controller.
        /// </summary>
        public SMSController SMSController => this.sMS.Value;

        /// <summary>
        /// Gets SessionManagementController controller.
        /// </summary>
        public SessionManagementController SessionManagementController => this.sessionManagement.Value;

        /// <summary>
        /// Gets ConnectivityCallbacksController controller.
        /// </summary>
        public ConnectivityCallbacksController ConnectivityCallbacksController => this.connectivityCallbacks.Value;

        /// <summary>
        /// Gets AccountRequestsController controller.
        /// </summary>
        public AccountRequestsController AccountRequestsController => this.accountRequests.Value;

        /// <summary>
        /// Gets ServicePlansController controller.
        /// </summary>
        public ServicePlansController ServicePlansController => this.servicePlans.Value;

        /// <summary>
        /// Gets DeviceDiagnosticsController controller.
        /// </summary>
        public DeviceDiagnosticsController DeviceDiagnosticsController => this.deviceDiagnostics.Value;

        /// <summary>
        /// Gets DeviceMonitoringController controller.
        /// </summary>
        public DeviceMonitoringController DeviceMonitoringController => this.deviceMonitoring.Value;

        /// <summary>
        /// Gets DeviceProfileManagementController controller.
        /// </summary>
        public DeviceProfileManagementController DeviceProfileManagementController => this.deviceProfileManagement.Value;

        /// <summary>
        /// Gets EUICCDeviceProfileManagementController controller.
        /// </summary>
        public EUICCDeviceProfileManagementController EUICCDeviceProfileManagementController => this.eUICCDeviceProfileManagement.Value;

        /// <summary>
        /// Gets DevicesLocationsController controller.
        /// </summary>
        public DevicesLocationsController DevicesLocationsController => this.devicesLocations.Value;

        /// <summary>
        /// Gets ExclusionsController controller.
        /// </summary>
        public ExclusionsController ExclusionsController => this.exclusions.Value;

        /// <summary>
        /// Gets DevicesLocationSubscriptionsController controller.
        /// </summary>
        public DevicesLocationSubscriptionsController DevicesLocationSubscriptionsController => this.devicesLocationSubscriptions.Value;

        /// <summary>
        /// Gets DeviceLocationCallbacksController controller.
        /// </summary>
        public DeviceLocationCallbacksController DeviceLocationCallbacksController => this.deviceLocationCallbacks.Value;

        /// <summary>
        /// Gets UsageTriggerManagementController controller.
        /// </summary>
        public UsageTriggerManagementController UsageTriggerManagementController => this.usageTriggerManagement.Value;

        /// <summary>
        /// Gets BillingController controller.
        /// </summary>
        public BillingController BillingController => this.billing.Value;

        /// <summary>
        /// Gets SoftwareManagementSubscriptionsV1Controller controller.
        /// </summary>
        public SoftwareManagementSubscriptionsV1Controller SoftwareManagementSubscriptionsV1Controller => this.softwareManagementSubscriptionsV1.Value;

        /// <summary>
        /// Gets SoftwareManagementLicensesV1Controller controller.
        /// </summary>
        public SoftwareManagementLicensesV1Controller SoftwareManagementLicensesV1Controller => this.softwareManagementLicensesV1.Value;

        /// <summary>
        /// Gets FirmwareV1Controller controller.
        /// </summary>
        public FirmwareV1Controller FirmwareV1Controller => this.firmwareV1.Value;

        /// <summary>
        /// Gets SoftwareManagementCallbacksV1Controller controller.
        /// </summary>
        public SoftwareManagementCallbacksV1Controller SoftwareManagementCallbacksV1Controller => this.softwareManagementCallbacksV1.Value;

        /// <summary>
        /// Gets SoftwareManagementReportsV1Controller controller.
        /// </summary>
        public SoftwareManagementReportsV1Controller SoftwareManagementReportsV1Controller => this.softwareManagementReportsV1.Value;

        /// <summary>
        /// Gets SoftwareManagementSubscriptionsV2Controller controller.
        /// </summary>
        public SoftwareManagementSubscriptionsV2Controller SoftwareManagementSubscriptionsV2Controller => this.softwareManagementSubscriptionsV2.Value;

        /// <summary>
        /// Gets SoftwareManagementLicensesV2Controller controller.
        /// </summary>
        public SoftwareManagementLicensesV2Controller SoftwareManagementLicensesV2Controller => this.softwareManagementLicensesV2.Value;

        /// <summary>
        /// Gets CampaignsV2Controller controller.
        /// </summary>
        public CampaignsV2Controller CampaignsV2Controller => this.campaignsV2.Value;

        /// <summary>
        /// Gets SoftwareManagementCallbacksV2Controller controller.
        /// </summary>
        public SoftwareManagementCallbacksV2Controller SoftwareManagementCallbacksV2Controller => this.softwareManagementCallbacksV2.Value;

        /// <summary>
        /// Gets SoftwareManagementReportsV2Controller controller.
        /// </summary>
        public SoftwareManagementReportsV2Controller SoftwareManagementReportsV2Controller => this.softwareManagementReportsV2.Value;

        /// <summary>
        /// Gets ClientLoggingController controller.
        /// </summary>
        public ClientLoggingController ClientLoggingController => this.clientLogging.Value;

        /// <summary>
        /// Gets ServerLoggingController controller.
        /// </summary>
        public ServerLoggingController ServerLoggingController => this.serverLogging.Value;

        /// <summary>
        /// Gets ConfigurationFilesController controller.
        /// </summary>
        public ConfigurationFilesController ConfigurationFilesController => this.configurationFiles.Value;

        /// <summary>
        /// Gets SoftwareManagementSubscriptionsV3Controller controller.
        /// </summary>
        public SoftwareManagementSubscriptionsV3Controller SoftwareManagementSubscriptionsV3Controller => this.softwareManagementSubscriptionsV3.Value;

        /// <summary>
        /// Gets SoftwareManagementLicensesV3Controller controller.
        /// </summary>
        public SoftwareManagementLicensesV3Controller SoftwareManagementLicensesV3Controller => this.softwareManagementLicensesV3.Value;

        /// <summary>
        /// Gets CampaignsV3Controller controller.
        /// </summary>
        public CampaignsV3Controller CampaignsV3Controller => this.campaignsV3.Value;

        /// <summary>
        /// Gets SoftwareManagementReportsV3Controller controller.
        /// </summary>
        public SoftwareManagementReportsV3Controller SoftwareManagementReportsV3Controller => this.softwareManagementReportsV3.Value;

        /// <summary>
        /// Gets FirmwareV3Controller controller.
        /// </summary>
        public FirmwareV3Controller FirmwareV3Controller => this.firmwareV3.Value;

        /// <summary>
        /// Gets AccountDevicesController controller.
        /// </summary>
        public AccountDevicesController AccountDevicesController => this.accountDevices.Value;

        /// <summary>
        /// Gets SoftwareManagementCallbacksV3Controller controller.
        /// </summary>
        public SoftwareManagementCallbacksV3Controller SoftwareManagementCallbacksV3Controller => this.softwareManagementCallbacksV3.Value;

        /// <summary>
        /// Gets SIMSecureForIoTLicensesController controller.
        /// </summary>
        public SIMSecureForIoTLicensesController SIMSecureForIoTLicensesController => this.sIMSecureForIoTLicenses.Value;

        /// <summary>
        /// Gets AccountSubscriptionsController controller.
        /// </summary>
        public AccountSubscriptionsController AccountSubscriptionsController => this.accountSubscriptions.Value;

        /// <summary>
        /// Gets DiagnosticsSubscriptionsController controller.
        /// </summary>
        public DiagnosticsSubscriptionsController DiagnosticsSubscriptionsController => this.diagnosticsSubscriptions.Value;

        /// <summary>
        /// Gets DiagnosticsObservationsController controller.
        /// </summary>
        public DiagnosticsObservationsController DiagnosticsObservationsController => this.diagnosticsObservations.Value;

        /// <summary>
        /// Gets DiagnosticsHistoryController controller.
        /// </summary>
        public DiagnosticsHistoryController DiagnosticsHistoryController => this.diagnosticsHistory.Value;

        /// <summary>
        /// Gets DiagnosticsSettingsController controller.
        /// </summary>
        public DiagnosticsSettingsController DiagnosticsSettingsController => this.diagnosticsSettings.Value;

        /// <summary>
        /// Gets DiagnosticsCallbacksController controller.
        /// </summary>
        public DiagnosticsCallbacksController DiagnosticsCallbacksController => this.diagnosticsCallbacks.Value;

        /// <summary>
        /// Gets DiagnosticsFactoryResetController controller.
        /// </summary>
        public DiagnosticsFactoryResetController DiagnosticsFactoryResetController => this.diagnosticsFactoryReset.Value;

        /// <summary>
        /// Gets TargetsController controller.
        /// </summary>
        public TargetsController TargetsController => this.targets.Value;

        /// <summary>
        /// Gets CloudConnectorSubscriptionsController controller.
        /// </summary>
        public CloudConnectorSubscriptionsController CloudConnectorSubscriptionsController => this.cloudConnectorSubscriptions.Value;

        /// <summary>
        /// Gets CloudConnectorDevicesController controller.
        /// </summary>
        public CloudConnectorDevicesController CloudConnectorDevicesController => this.cloudConnectorDevices.Value;

        /// <summary>
        /// Gets HPLDeviceManagementController controller.
        /// </summary>
        public HPLDeviceManagementController HPLDeviceManagementController => this.hPLDeviceManagement.Value;

        /// <summary>
        /// Gets DeviceServiceManagementController controller.
        /// </summary>
        public DeviceServiceManagementController DeviceServiceManagementController => this.deviceServiceManagement.Value;

        /// <summary>
        /// Gets DeviceReportsController controller.
        /// </summary>
        public DeviceReportsController DeviceReportsController => this.deviceReports.Value;

        /// <summary>
        /// Gets HyperPreciseLocationCallbacksController controller.
        /// </summary>
        public HyperPreciseLocationCallbacksController HyperPreciseLocationCallbacksController => this.hyperPreciseLocationCallbacks.Value;

        /// <summary>
        /// Gets DeviceCredentialManagementController controller.
        /// </summary>
        public DeviceCredentialManagementController DeviceCredentialManagementController => this.deviceCredentialManagement.Value;

        /// <summary>
        /// Gets AnomalySettingsController controller.
        /// </summary>
        public AnomalySettingsController AnomalySettingsController => this.anomalySettings.Value;

        /// <summary>
        /// Gets AnomalyTriggersController controller.
        /// </summary>
        public AnomalyTriggersController AnomalyTriggersController => this.anomalyTriggers.Value;

        /// <summary>
        /// Gets AnomalyTriggersV2Controller controller.
        /// </summary>
        public AnomalyTriggersV2Controller AnomalyTriggersV2Controller => this.anomalyTriggersV2.Value;

        /// <summary>
        /// Gets WirelessNetworkPerformanceController controller.
        /// </summary>
        public WirelessNetworkPerformanceController WirelessNetworkPerformanceController => this.wirelessNetworkPerformance.Value;

        /// <summary>
        /// Gets ManagingESIMProfilesController controller.
        /// </summary>
        public ManagingESIMProfilesController ManagingESIMProfilesController => this.managingESIMProfiles.Value;

        /// <summary>
        /// Gets DeviceSMSMessagingController controller.
        /// </summary>
        public DeviceSMSMessagingController DeviceSMSMessagingController => this.deviceSMSMessaging.Value;

        /// <summary>
        /// Gets DeviceActionsController controller.
        /// </summary>
        public DeviceActionsController DeviceActionsController => this.deviceActions.Value;

        /// <summary>
        /// Gets ThingSpaceQualityOfServiceAPIActionsController controller.
        /// </summary>
        public ThingSpaceQualityOfServiceAPIActionsController ThingSpaceQualityOfServiceAPIActionsController => this.thingSpaceQualityOfServiceAPIActions.Value;

        /// <summary>
        /// Gets PWNController controller.
        /// </summary>
        public PWNController PWNController => this.pWN.Value;

        /// <summary>
        /// Gets PromotionPeriodInformationController controller.
        /// </summary>
        public PromotionPeriodInformationController PromotionPeriodInformationController => this.promotionPeriodInformation.Value;

        /// <summary>
        /// Gets RetrieveTheTriggersController controller.
        /// </summary>
        public RetrieveTheTriggersController RetrieveTheTriggersController => this.retrieveTheTriggers.Value;

        /// <summary>
        /// Gets UpdateTriggersController controller.
        /// </summary>
        public UpdateTriggersController UpdateTriggersController => this.updateTriggers.Value;

        /// <summary>
        /// Gets SIMActionsController controller.
        /// </summary>
        public SIMActionsController SIMActionsController => this.sIMActions.Value;

        /// <summary>
        /// Gets GlobalReportingController controller.
        /// </summary>
        public GlobalReportingController GlobalReportingController => this.globalReporting.Value;

        /// <summary>
        /// Gets DeviceRoleController controller.
        /// </summary>
        public DeviceRoleController DeviceRoleController => this.deviceRoleController.Value;

        /// <summary>
        /// Gets MapDataManagerController controller.
        /// </summary>
        public MapDataManagerController MapDataManagerController => this.mapDataManager.Value;

        /// <summary>
        /// Gets RetrieveRatePlanListController controller.
        /// </summary>
        public RetrieveRatePlanListController RetrieveRatePlanListController => this.retrieveRatePlanList.Value;

        /// <summary>
        /// Gets CreatePricePlanTriggersController controller.
        /// </summary>
        public CreatePricePlanTriggersController CreatePricePlanTriggersController => this.createPricePlanTriggers.Value;

        /// <summary>
        /// Gets UpdatePricePlanTriggersController controller.
        /// </summary>
        public UpdatePricePlanTriggersController UpdatePricePlanTriggersController => this.updatePricePlanTriggers.Value;

        /// <summary>
        /// Gets M5gBIDeviceActionsController controller.
        /// </summary>
        public M5gBIDeviceActionsController M5gBIDeviceActionsController => this.m5gBIDeviceActions.Value;

        /// <summary>
        /// Gets SensorInsightsSensorsController controller.
        /// </summary>
        public SensorInsightsSensorsController SensorInsightsSensorsController => this.sensorInsightsSensors.Value;

        /// <summary>
        /// Gets SensorInsightsDevicesController controller.
        /// </summary>
        public SensorInsightsDevicesController SensorInsightsDevicesController => this.sensorInsightsDevices.Value;

        /// <summary>
        /// Gets SensorInsightsGatewaysController controller.
        /// </summary>
        public SensorInsightsGatewaysController SensorInsightsGatewaysController => this.sensorInsightsGateways.Value;

        /// <summary>
        /// Gets SensorInsightsSmartAlertsController controller.
        /// </summary>
        public SensorInsightsSmartAlertsController SensorInsightsSmartAlertsController => this.sensorInsightsSmartAlerts.Value;

        /// <summary>
        /// Gets SensorInsightsRulesController controller.
        /// </summary>
        public SensorInsightsRulesController SensorInsightsRulesController => this.sensorInsightsRules.Value;

        /// <summary>
        /// Gets SensorInsightsHealthScoreController controller.
        /// </summary>
        public SensorInsightsHealthScoreController SensorInsightsHealthScoreController => this.sensorInsightsHealthScore.Value;

        /// <summary>
        /// Gets SensorInsightsNotificationGroupsController controller.
        /// </summary>
        public SensorInsightsNotificationGroupsController SensorInsightsNotificationGroupsController => this.sensorInsightsNotificationGroups.Value;

        /// <summary>
        /// Gets SensorInsightsUsersController controller.
        /// </summary>
        public SensorInsightsUsersController SensorInsightsUsersController => this.sensorInsightsUsers.Value;

        /// <summary>
        /// Gets SensorInsightsDeviceProfileController controller.
        /// </summary>
        public SensorInsightsDeviceProfileController SensorInsightsDeviceProfileController => this.sensorInsightsDeviceProfile.Value;

        /// <summary>
        /// Gets SensorInsightsSmartAlertMetricsController controller.
        /// </summary>
        public SensorInsightsSmartAlertMetricsController SensorInsightsSmartAlertMetricsController => this.sensorInsightsSmartAlertMetrics.Value;

        /// <summary>
        /// Gets APIController controller.
        /// </summary>
        public APIController APIController => this.client.Value;

        /// <summary>
        /// Gets OauthAuthorizationController controller.
        /// </summary>
        public OauthAuthorizationController OauthAuthorizationController => this.oauthAuthorization.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with ThingspaceOauth.
        /// </summary>
        public IThingspaceOauthCredentials ThingspaceOauthCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with ThingspaceOauth.
        /// </summary>
        public ThingspaceOauthModel ThingspaceOauthModel { get; private set; }

        /// <summary>
        /// Gets the credentials to use with VZM2MToken.
        /// </summary>
        public IVZM2mTokenCredentials VZM2mTokenCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with VZM2MToken.
        /// </summary>
        public VZM2mTokenModel VZM2mTokenModel { get; private set; }

        /// <summary>
        /// Gets the credentials to use with SessionToken.
        /// </summary>
        public ISessionTokenCredentials SessionTokenCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with SessionToken.
        /// </summary>
        public SessionTokenModel SessionTokenModel { get; private set; }

        /// <summary>
        /// Gets the credentials to use with ThingspaceOauth1.
        /// </summary>
        public IThingspaceOauth1Credentials ThingspaceOauth1Credentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with ThingspaceOauth1.
        /// </summary>
        public ThingspaceOauth1Model ThingspaceOauth1Model { get; private set; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:THINGSPACE.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.Thingspace)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the VerizonClient using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .HttpCallback(httpCallback)
                .HttpClientConfig(config => config.Build());

            if (ThingspaceOauthModel != null)
            {
                builder.ThingspaceOauthCredentials(ThingspaceOauthModel.ToBuilder().Build());
            }

            if (VZM2mTokenModel != null)
            {
                builder.VZM2mTokenCredentials(VZM2mTokenModel.ToBuilder().Build());
            }

            if (SessionTokenModel != null)
            {
                builder.SessionTokenCredentials(SessionTokenModel.ToBuilder().Build());
            }

            if (ThingspaceOauth1Model != null)
            {
                builder.ThingspaceOauth1Credentials(ThingspaceOauth1Model.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> VerizonClient.</returns>
        internal static VerizonClient CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("VERIZON_STANDARD_ENVIRONMENT");
            string oauthClientId = System.Environment.GetEnvironmentVariable("VERIZON_STANDARD_OAUTH_CLIENT_ID");
            string oauthClientSecret = System.Environment.GetEnvironmentVariable("VERIZON_STANDARD_OAUTH_CLIENT_SECRET");
            string vZM2mToken = System.Environment.GetEnvironmentVariable("VERIZON_STANDARD_VZ_M2M_TOKEN");
            string sessionToken = System.Environment.GetEnvironmentVariable("VERIZON_STANDARD_SESSION_TOKEN");
            string oauthClientId2 = System.Environment.GetEnvironmentVariable("VERIZON_STANDARD_OAUTH_CLIENT_ID_2");
            string oauthClientSecret2 = System.Environment.GetEnvironmentVariable("VERIZON_STANDARD_OAUTH_CLIENT_SECRET_2");

            if (environment != null)
            {
                builder.Environment(CoreHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (oauthClientId != null && oauthClientSecret != null)
            {
                builder.ThingspaceOauthCredentials(new ThingspaceOauthModel
                .Builder(oauthClientId, oauthClientSecret)
                .Build());
            }

            if (vZM2mToken != null)
            {
                builder.VZM2mTokenCredentials(new VZM2mTokenModel
                .Builder(vZM2mToken)
                .Build());
            }

            if (sessionToken != null)
            {
                builder.SessionTokenCredentials(new SessionTokenModel
                .Builder(sessionToken)
                .Build());
            }

            if (oauthClientId2 != null && oauthClientSecret2 != null)
            {
                builder.ThingspaceOauth1Credentials(new ThingspaceOauth1Model
                .Builder(oauthClientId2, oauthClientSecret2)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Creates the client from configuration.
        /// </summary>
        /// <returns> VerizonClient.</returns>
        public static VerizonClient FromConfiguration(IConfigurationSection configuration) =>
            Builder.FromConfiguration(configuration).Build();

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment _environment = Verizon.Standard.Environment.Production;
            private ThingspaceOauthModel _thingspaceOauthModel = new ThingspaceOauthModel();
            private VZM2mTokenModel _vZM2mTokenModel = new VZM2mTokenModel();
            private SessionTokenModel _sessionTokenModel = new SessionTokenModel();
            private ThingspaceOauth1Model _thingspaceOauth1Model = new ThingspaceOauth1Model();
            private HttpClientConfiguration.Builder _httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback _httpCallback;

            /// <summary>
            /// Sets credentials for ThingspaceOauth.
            /// </summary>
            /// <param name="thingspaceOauthModel">ThingspaceOauthModel.</param>
            /// <returns>Builder.</returns>
            public Builder ThingspaceOauthCredentials(ThingspaceOauthModel thingspaceOauthModel)
            {
                _thingspaceOauthModel = thingspaceOauthModel ??
                    throw new ArgumentNullException(nameof(thingspaceOauthModel));
                return this;
            }

            /// <summary>
            /// Sets credentials for VZM2MToken.
            /// </summary>
            /// <param name="vZM2mTokenModel">VZM2mTokenModel.</param>
            /// <returns>Builder.</returns>
            public Builder VZM2mTokenCredentials(VZM2mTokenModel vZM2mTokenModel)
            {
                _vZM2mTokenModel = vZM2mTokenModel ??
                    throw new ArgumentNullException(nameof(vZM2mTokenModel));
                return this;
            }

            /// <summary>
            /// Sets credentials for SessionToken.
            /// </summary>
            /// <param name="sessionTokenModel">SessionTokenModel.</param>
            /// <returns>Builder.</returns>
            public Builder SessionTokenCredentials(SessionTokenModel sessionTokenModel)
            {
                _sessionTokenModel = sessionTokenModel ??
                    throw new ArgumentNullException(nameof(sessionTokenModel));
                return this;
            }

            /// <summary>
            /// Sets credentials for ThingspaceOauth1.
            /// </summary>
            /// <param name="thingspaceOauth1Model">ThingspaceOauth1Model.</param>
            /// <returns>Builder.</returns>
            public Builder ThingspaceOauth1Credentials(ThingspaceOauth1Model thingspaceOauth1Model)
            {
                _thingspaceOauth1Model = thingspaceOauth1Model ??
                    throw new ArgumentNullException(nameof(thingspaceOauth1Model));
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                _environment = environment;
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(_httpClientConfig);
                return this;
            }

            private Builder HttpClientConfig(HttpClientConfiguration.Builder httpClientConfigurationBuilder)
            {
                if (httpClientConfigurationBuilder != null)
                {
                    _httpClientConfig = httpClientConfigurationBuilder;
                }

                return this;
            }

            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                _httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the VerizonClient using the values provided for the builder.
            /// </summary>
            /// <returns>VerizonClient.</returns>
            public VerizonClient Build()
            {
                if (_thingspaceOauthModel.OauthClientId == null || _thingspaceOauthModel.OauthClientSecret == null)
                {
                    _thingspaceOauthModel = null;
                }
                if (_vZM2mTokenModel.VZM2mToken == null)
                {
                    _vZM2mTokenModel = null;
                }
                if (_sessionTokenModel.SessionToken == null)
                {
                    _sessionTokenModel = null;
                }
                if (_thingspaceOauth1Model.OauthClientId == null || _thingspaceOauth1Model.OauthClientSecret == null)
                {
                    _thingspaceOauth1Model = null;
                }
                return new VerizonClient(
                    _environment,
                    _thingspaceOauthModel,
                    _vZM2mTokenModel,
                    _sessionTokenModel,
                    _thingspaceOauth1Model,
                    _httpCallback,
                    _httpClientConfig.Build());
            }

            /// <summary>
            /// Creates the client builder from configuration.
            /// </summary>
            /// <returns> Builder.</returns>
            public static Builder FromConfiguration(IConfigurationSection config)
            {
                var builder = new Builder();
                var options = config.Get<VerizonClientOptions>();
                if (options == null) return builder;
                if (options.Environment != null)
                    builder.Environment(options.Environment.Value);
                if (options.ThingspaceOauthCredentials != null)
                    builder.ThingspaceOauthCredentials(ThingspaceOauthModel.FromOptions(options.ThingspaceOauthCredentials));
                if (options.VZM2mTokenCredentials != null)
                    builder.VZM2mTokenCredentials(VZM2mTokenModel.FromOptions(options.VZM2mTokenCredentials));
                if (options.SessionTokenCredentials != null)
                    builder.SessionTokenCredentials(SessionTokenModel.FromOptions(options.SessionTokenCredentials));
                if (options.ThingspaceOauth1Credentials != null)
                    builder.ThingspaceOauth1Credentials(ThingspaceOauth1Model.FromOptions(options.ThingspaceOauth1Credentials));
                if (options.HttpClientConfig != null)
                    builder.HttpClientConfig(Http.Client.HttpClientConfiguration.FromOptions(options.HttpClientConfig));
                return builder;
            }
        }

        public class VerizonClientOptions
        {
            public Environment? Environment { get; set; }
            public ThingspaceOauthModelOptions ThingspaceOauthCredentials { get; set; }
            public VZM2MTokenModelOptions VZM2mTokenCredentials { get; set; }
            public SessionTokenModelOptions SessionTokenCredentials { get; set; }
            public ThingspaceOauth1ModelOptions ThingspaceOauth1Credentials { get; set; }
            public HttpClientConfigurationOptions HttpClientConfig { get; set; }
        }
    }
}
