// <copyright file="DeactivateDeviceListIds.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace Verizon.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for any-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<DeactivateDeviceListIds>),
        new[] {
            typeof(DeviceIdCase),
            typeof(PropertyDeviceIdCase)
        },
        false
    )]
    public abstract class DeactivateDeviceListIds
    {
        /// <summary>
        /// This is DeviceId case.
        /// </summary>
        /// <returns>
        /// The DeactivateDeviceListIds instance, wrapping the provided DeviceId value.
        /// </returns>
        public static DeactivateDeviceListIds FromDeviceId(DeviceId deviceId)
        {
            return new DeviceIdCase().Set(deviceId);
        }

        /// <summary>
        /// This is PropertyDeviceId case.
        /// </summary>
        /// <returns>
        /// The DeactivateDeviceListIds instance, wrapping the provided PropertyDeviceId value.
        /// </returns>
        public static DeactivateDeviceListIds FromPropertyDeviceId(PropertyDeviceId propertyDeviceId)
        {
            return new PropertyDeviceIdCase().Set(propertyDeviceId);
        }

        /// <summary>
        /// Method to match from the provided any-of cases. Here parameters
        /// represents the callback functions for any-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<DeviceId, T> deviceId, Func<PropertyDeviceId, T> propertyDeviceId);

        /// <summary>
        /// Method to match from the provided any-of cases. The parameters represent
        /// optional callback functions for any-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<DeviceId, T> deviceId = null, Func<PropertyDeviceId, T> propertyDeviceId = null) =>
                Match(deviceId, propertyDeviceId);

        [JsonConverter(typeof(UnionTypeCaseConverter<DeviceIdCase, DeviceId>))]
        private sealed class DeviceIdCase : DeactivateDeviceListIds, ICaseValue<DeviceIdCase, DeviceId>
        {
            public DeviceId Value;

            public override T Match<T>(Func<DeviceId, T> deviceId, Func<PropertyDeviceId, T> propertyDeviceId) =>
                   deviceId != null ? deviceId(Value) : default;

            public DeviceIdCase Set(DeviceId value)
            {
                Value = value;
                return this;
            }

            public DeviceId Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is DeviceIdCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<PropertyDeviceIdCase, PropertyDeviceId>))]
        private sealed class PropertyDeviceIdCase : DeactivateDeviceListIds, ICaseValue<PropertyDeviceIdCase, PropertyDeviceId>
        {
            public PropertyDeviceId Value;

            public override T Match<T>(Func<DeviceId, T> deviceId, Func<PropertyDeviceId, T> propertyDeviceId) =>
                   propertyDeviceId != null ? propertyDeviceId(Value) : default;

            public PropertyDeviceIdCase Set(PropertyDeviceId value)
            {
                Value = value;
                return this;
            }

            public PropertyDeviceId Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is PropertyDeviceIdCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }
    }
}