// <copyright file="ESIMDeviceListDeviceIds.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace Verizon.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for any-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<ESIMDeviceListDeviceIds>),
        new[] {
            typeof(ESIMDeviceIdCase),
            typeof(DeviceId2Case)
        },
        false
    )]
    public abstract class ESIMDeviceListDeviceIds
    {
        /// <summary>
        /// This is eSIMDeviceId case.
        /// </summary>
        /// <returns>
        /// The ESIMDeviceListDeviceIds instance, wrapping the provided ESIMDeviceId value.
        /// </returns>
        public static ESIMDeviceListDeviceIds FromESIMDeviceId(ESIMDeviceId eSIMDeviceId)
        {
            return new ESIMDeviceIdCase().Set(eSIMDeviceId);
        }

        /// <summary>
        /// This is DeviceId2 case.
        /// </summary>
        /// <returns>
        /// The ESIMDeviceListDeviceIds instance, wrapping the provided DeviceId2 value.
        /// </returns>
        public static ESIMDeviceListDeviceIds FromDeviceId2(DeviceId2 deviceId2)
        {
            return new DeviceId2Case().Set(deviceId2);
        }

        /// <summary>
        /// Method to match from the provided any-of cases. Here parameters
        /// represents the callback functions for any-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<ESIMDeviceId, T> eSIMDeviceId, Func<DeviceId2, T> deviceId2);

        /// <summary>
        /// Method to match from the provided any-of cases. The parameters represent
        /// optional callback functions for any-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<ESIMDeviceId, T> eSIMDeviceId = null, Func<DeviceId2, T> deviceId2 = null) =>
                Match(eSIMDeviceId, deviceId2);

        [JsonConverter(typeof(UnionTypeCaseConverter<ESIMDeviceIdCase, ESIMDeviceId>))]
        private sealed class ESIMDeviceIdCase : ESIMDeviceListDeviceIds, ICaseValue<ESIMDeviceIdCase, ESIMDeviceId>
        {
            public ESIMDeviceId Value;

            public override T Match<T>(Func<ESIMDeviceId, T> eSIMDeviceId, Func<DeviceId2, T> deviceId2) =>
                   eSIMDeviceId != null ? eSIMDeviceId(Value) : default;

            public ESIMDeviceIdCase Set(ESIMDeviceId value)
            {
                Value = value;
                return this;
            }

            public ESIMDeviceId Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is ESIMDeviceIdCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<DeviceId2Case, DeviceId2>))]
        private sealed class DeviceId2Case : ESIMDeviceListDeviceIds, ICaseValue<DeviceId2Case, DeviceId2>
        {
            public DeviceId2 Value;

            public override T Match<T>(Func<ESIMDeviceId, T> eSIMDeviceId, Func<DeviceId2, T> deviceId2) =>
                   deviceId2 != null ? deviceId2(Value) : default;

            public DeviceId2Case Set(DeviceId2 value)
            {
                Value = value;
                return this;
            }

            public DeviceId2 Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is DeviceId2Case other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }
    }
}