// <copyright file="KeysChunk.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace Verizon.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for any-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<KeysChunk>),
        new[] {
            typeof(KeyServicePlanCase),
            typeof(KeyDataPercentage50Case),
            typeof(KeysmsPercentage50Case),
            typeof(NoOfDaysB4PromoExpCase),
            typeof(EnablePromoExpCase)
        },
        false
    )]
    public abstract class KeysChunk
    {
        /// <summary>
        /// This is keyServicePlan case.
        /// </summary>
        /// <returns>
        /// The KeysChunk instance, wrapping the provided KeyServicePlan value.
        /// </returns>
        public static KeysChunk FromKeyServicePlan(KeyServicePlan keyServicePlan)
        {
            return new KeyServicePlanCase().Set(keyServicePlan);
        }

        /// <summary>
        /// This is keyDataPercentage50 case.
        /// </summary>
        /// <returns>
        /// The KeysChunk instance, wrapping the provided KeyDataPercentage50 value.
        /// </returns>
        public static KeysChunk FromKeyDataPercentage50(KeyDataPercentage50 keyDataPercentage50)
        {
            return new KeyDataPercentage50Case().Set(keyDataPercentage50);
        }

        /// <summary>
        /// This is keysmsPercentage50 case.
        /// </summary>
        /// <returns>
        /// The KeysChunk instance, wrapping the provided KeysmsPercentage50 value.
        /// </returns>
        public static KeysChunk FromKeysmsPercentage50(KeysmsPercentage50 keysmsPercentage50)
        {
            return new KeysmsPercentage50Case().Set(keysmsPercentage50);
        }

        /// <summary>
        /// This is NoOfDaysB4PromoExp case.
        /// </summary>
        /// <returns>
        /// The KeysChunk instance, wrapping the provided NoOfDaysB4PromoExp value.
        /// </returns>
        public static KeysChunk FromNoOfDaysB4PromoExp(NoOfDaysB4PromoExp noOfDaysB4PromoExp)
        {
            return new NoOfDaysB4PromoExpCase().Set(noOfDaysB4PromoExp);
        }

        /// <summary>
        /// This is EnablePromoExp case.
        /// </summary>
        /// <returns>
        /// The KeysChunk instance, wrapping the provided EnablePromoExp value.
        /// </returns>
        public static KeysChunk FromEnablePromoExp(EnablePromoExp enablePromoExp)
        {
            return new EnablePromoExpCase().Set(enablePromoExp);
        }

        /// <summary>
        /// Method to match from the provided any-of cases. Here parameters
        /// represents the callback functions for any-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<KeyServicePlan, T> keyServicePlan,
            Func<KeyDataPercentage50, T> keyDataPercentage50,
            Func<KeysmsPercentage50, T> keysmsPercentage50,
            Func<NoOfDaysB4PromoExp, T> noOfDaysB4PromoExp,
            Func<EnablePromoExp, T> enablePromoExp);

        /// <summary>
        /// Method to match from the provided any-of cases. The parameters represent
        /// optional callback functions for any-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<KeyServicePlan, T> keyServicePlan = null,
            Func<KeyDataPercentage50, T> keyDataPercentage50 = null,
            Func<KeysmsPercentage50, T> keysmsPercentage50 = null,
            Func<NoOfDaysB4PromoExp, T> noOfDaysB4PromoExp = null,
            Func<EnablePromoExp, T> enablePromoExp = null) =>
                Match(keyServicePlan, keyDataPercentage50, keysmsPercentage50, noOfDaysB4PromoExp, enablePromoExp);

        [JsonConverter(typeof(UnionTypeCaseConverter<KeyServicePlanCase, KeyServicePlan>))]
        private sealed class KeyServicePlanCase : KeysChunk, ICaseValue<KeyServicePlanCase, KeyServicePlan>
        {
            public KeyServicePlan Value;

            public override T Match<T>(
                Func<KeyServicePlan, T> keyServicePlan,
                Func<KeyDataPercentage50, T> keyDataPercentage50,
                Func<KeysmsPercentage50, T> keysmsPercentage50,
                Func<NoOfDaysB4PromoExp, T> noOfDaysB4PromoExp,
                Func<EnablePromoExp, T> enablePromoExp) =>
                   keyServicePlan != null ? keyServicePlan(Value) : default;

            public KeyServicePlanCase Set(KeyServicePlan value)
            {
                Value = value;
                return this;
            }

            public KeyServicePlan Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is KeyServicePlanCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<KeyDataPercentage50Case, KeyDataPercentage50>))]
        private sealed class KeyDataPercentage50Case : KeysChunk, ICaseValue<KeyDataPercentage50Case, KeyDataPercentage50>
        {
            public KeyDataPercentage50 Value;

            public override T Match<T>(
                Func<KeyServicePlan, T> keyServicePlan,
                Func<KeyDataPercentage50, T> keyDataPercentage50,
                Func<KeysmsPercentage50, T> keysmsPercentage50,
                Func<NoOfDaysB4PromoExp, T> noOfDaysB4PromoExp,
                Func<EnablePromoExp, T> enablePromoExp) =>
                   keyDataPercentage50 != null ? keyDataPercentage50(Value) : default;

            public KeyDataPercentage50Case Set(KeyDataPercentage50 value)
            {
                Value = value;
                return this;
            }

            public KeyDataPercentage50 Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is KeyDataPercentage50Case other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<KeysmsPercentage50Case, KeysmsPercentage50>))]
        private sealed class KeysmsPercentage50Case : KeysChunk, ICaseValue<KeysmsPercentage50Case, KeysmsPercentage50>
        {
            public KeysmsPercentage50 Value;

            public override T Match<T>(
                Func<KeyServicePlan, T> keyServicePlan,
                Func<KeyDataPercentage50, T> keyDataPercentage50,
                Func<KeysmsPercentage50, T> keysmsPercentage50,
                Func<NoOfDaysB4PromoExp, T> noOfDaysB4PromoExp,
                Func<EnablePromoExp, T> enablePromoExp) =>
                   keysmsPercentage50 != null ? keysmsPercentage50(Value) : default;

            public KeysmsPercentage50Case Set(KeysmsPercentage50 value)
            {
                Value = value;
                return this;
            }

            public KeysmsPercentage50 Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is KeysmsPercentage50Case other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<NoOfDaysB4PromoExpCase, NoOfDaysB4PromoExp>))]
        private sealed class NoOfDaysB4PromoExpCase : KeysChunk, ICaseValue<NoOfDaysB4PromoExpCase, NoOfDaysB4PromoExp>
        {
            public NoOfDaysB4PromoExp Value;

            public override T Match<T>(
                Func<KeyServicePlan, T> keyServicePlan,
                Func<KeyDataPercentage50, T> keyDataPercentage50,
                Func<KeysmsPercentage50, T> keysmsPercentage50,
                Func<NoOfDaysB4PromoExp, T> noOfDaysB4PromoExp,
                Func<EnablePromoExp, T> enablePromoExp) =>
                   noOfDaysB4PromoExp != null ? noOfDaysB4PromoExp(Value) : default;

            public NoOfDaysB4PromoExpCase Set(NoOfDaysB4PromoExp value)
            {
                Value = value;
                return this;
            }

            public NoOfDaysB4PromoExp Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is NoOfDaysB4PromoExpCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<EnablePromoExpCase, EnablePromoExp>))]
        private sealed class EnablePromoExpCase : KeysChunk, ICaseValue<EnablePromoExpCase, EnablePromoExp>
        {
            public EnablePromoExp Value;

            public override T Match<T>(
                Func<KeyServicePlan, T> keyServicePlan,
                Func<KeyDataPercentage50, T> keyDataPercentage50,
                Func<KeysmsPercentage50, T> keysmsPercentage50,
                Func<NoOfDaysB4PromoExp, T> noOfDaysB4PromoExp,
                Func<EnablePromoExp, T> enablePromoExp) =>
                   enablePromoExp != null ? enablePromoExp(Value) : default;

            public EnablePromoExpCase Set(EnablePromoExp value)
            {
                Value = value;
                return this;
            }

            public EnablePromoExp Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is EnablePromoExpCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }
    }
}