// <copyright file="M5gBiactivateRequestDeviceListWithServiceAddress.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace Verizon.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for any-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<M5gBiactivateRequestDeviceListWithServiceAddress>),
        new[] {
            typeof(M5gBideviceIdarrayCase),
            typeof(M5gBiaddressAndcustomerinfoCase)
        },
        false
    )]
    public abstract class M5gBiactivateRequestDeviceListWithServiceAddress
    {
        /// <summary>
        /// This is 5gbideviceIdarray case.
        /// </summary>
        /// <returns>
        /// The M5gBiactivateRequestDeviceListWithServiceAddress instance, wrapping the provided M5gBideviceIdarray value.
        /// </returns>
        public static M5gBiactivateRequestDeviceListWithServiceAddress From5gbideviceIdarray(M5gBideviceIdarray m5gBideviceIdarray)
        {
            return new M5gBideviceIdarrayCase().Set(m5gBideviceIdarray);
        }

        /// <summary>
        /// This is 5gbiaddressAndcustomerinfo case.
        /// </summary>
        /// <returns>
        /// The M5gBiactivateRequestDeviceListWithServiceAddress instance, wrapping the provided M5gBiaddressAndcustomerinfo value.
        /// </returns>
        public static M5gBiactivateRequestDeviceListWithServiceAddress From5gbiaddressAndcustomerinfo(M5gBiaddressAndcustomerinfo m5gBiaddressAndcustomerinfo)
        {
            return new M5gBiaddressAndcustomerinfoCase().Set(m5gBiaddressAndcustomerinfo);
        }

        /// <summary>
        /// Method to match from the provided any-of cases. Here parameters
        /// represents the callback functions for any-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<M5gBideviceIdarray, T> m5gBideviceIdarray, Func<M5gBiaddressAndcustomerinfo, T> m5gBiaddressAndcustomerinfo);

        /// <summary>
        /// Method to match from the provided any-of cases. The parameters represent
        /// optional callback functions for any-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<M5gBideviceIdarray, T> m5gBideviceIdarray = null, Func<M5gBiaddressAndcustomerinfo, T> m5gBiaddressAndcustomerinfo = null) =>
                Match(m5gBideviceIdarray, m5gBiaddressAndcustomerinfo);

        [JsonConverter(typeof(UnionTypeCaseConverter<M5gBideviceIdarrayCase, M5gBideviceIdarray>))]
        private sealed class M5gBideviceIdarrayCase : M5gBiactivateRequestDeviceListWithServiceAddress, ICaseValue<M5gBideviceIdarrayCase, M5gBideviceIdarray>
        {
            public M5gBideviceIdarray Value;

            public override T Match<T>(Func<M5gBideviceIdarray, T> m5gBideviceIdarray, Func<M5gBiaddressAndcustomerinfo, T> m5gBiaddressAndcustomerinfo) =>
                   m5gBideviceIdarray != null ? m5gBideviceIdarray(Value) : default;

            public M5gBideviceIdarrayCase Set(M5gBideviceIdarray value)
            {
                Value = value;
                return this;
            }

            public M5gBideviceIdarray Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is M5gBideviceIdarrayCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<M5gBiaddressAndcustomerinfoCase, M5gBiaddressAndcustomerinfo>))]
        private sealed class M5gBiaddressAndcustomerinfoCase : M5gBiactivateRequestDeviceListWithServiceAddress, ICaseValue<M5gBiaddressAndcustomerinfoCase, M5gBiaddressAndcustomerinfo>
        {
            public M5gBiaddressAndcustomerinfo Value;

            public override T Match<T>(Func<M5gBideviceIdarray, T> m5gBideviceIdarray, Func<M5gBiaddressAndcustomerinfo, T> m5gBiaddressAndcustomerinfo) =>
                   m5gBiaddressAndcustomerinfo != null ? m5gBiaddressAndcustomerinfo(Value) : default;

            public M5gBiaddressAndcustomerinfoCase Set(M5gBiaddressAndcustomerinfo value)
            {
                Value = value;
                return this;
            }

            public M5gBiaddressAndcustomerinfo Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is M5gBiaddressAndcustomerinfoCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }
    }
}