// <copyright file="TriggerAttributesOptions2.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace Verizon.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for any-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<TriggerAttributesOptions2>),
        new[] {
            typeof(NotificationGroupNameTriggerAttributeCase),
            typeof(ServicePlanTriggerAttributeCase),
            typeof(DataPercentage50TriggerAttributeCase),
            typeof(DataPercentage75TriggerAttributeCase),
            typeof(DataPercentage90TriggerAttributeCase),
            typeof(DataPercentage100TriggerAttributeCase)
        },
        false
    )]
    public abstract class TriggerAttributesOptions2
    {
        /// <summary>
        /// This is NotificationGroupNameTriggerAttribute case.
        /// </summary>
        /// <returns>
        /// The TriggerAttributesOptions2 instance, wrapping the provided NotificationGroupNameTriggerAttribute value.
        /// </returns>
        public static TriggerAttributesOptions2 FromNotificationGroupNameTriggerAttribute(NotificationGroupNameTriggerAttribute notificationGroupNameTriggerAttribute)
        {
            return new NotificationGroupNameTriggerAttributeCase().Set(notificationGroupNameTriggerAttribute);
        }

        /// <summary>
        /// This is ServicePlanTriggerAttribute case.
        /// </summary>
        /// <returns>
        /// The TriggerAttributesOptions2 instance, wrapping the provided ServicePlanTriggerAttribute value.
        /// </returns>
        public static TriggerAttributesOptions2 FromServicePlanTriggerAttribute(ServicePlanTriggerAttribute servicePlanTriggerAttribute)
        {
            return new ServicePlanTriggerAttributeCase().Set(servicePlanTriggerAttribute);
        }

        /// <summary>
        /// This is DataPercentage50TriggerAttribute case.
        /// </summary>
        /// <returns>
        /// The TriggerAttributesOptions2 instance, wrapping the provided DataPercentage50TriggerAttribute value.
        /// </returns>
        public static TriggerAttributesOptions2 FromDataPercentage50TriggerAttribute(DataPercentage50TriggerAttribute dataPercentage50TriggerAttribute)
        {
            return new DataPercentage50TriggerAttributeCase().Set(dataPercentage50TriggerAttribute);
        }

        /// <summary>
        /// This is DataPercentage75TriggerAttribute case.
        /// </summary>
        /// <returns>
        /// The TriggerAttributesOptions2 instance, wrapping the provided DataPercentage75TriggerAttribute value.
        /// </returns>
        public static TriggerAttributesOptions2 FromDataPercentage75TriggerAttribute(DataPercentage75TriggerAttribute dataPercentage75TriggerAttribute)
        {
            return new DataPercentage75TriggerAttributeCase().Set(dataPercentage75TriggerAttribute);
        }

        /// <summary>
        /// This is DataPercentage90TriggerAttribute case.
        /// </summary>
        /// <returns>
        /// The TriggerAttributesOptions2 instance, wrapping the provided DataPercentage90TriggerAttribute value.
        /// </returns>
        public static TriggerAttributesOptions2 FromDataPercentage90TriggerAttribute(DataPercentage90TriggerAttribute dataPercentage90TriggerAttribute)
        {
            return new DataPercentage90TriggerAttributeCase().Set(dataPercentage90TriggerAttribute);
        }

        /// <summary>
        /// This is DataPercentage100TriggerAttribute case.
        /// </summary>
        /// <returns>
        /// The TriggerAttributesOptions2 instance, wrapping the provided DataPercentage100TriggerAttribute value.
        /// </returns>
        public static TriggerAttributesOptions2 FromDataPercentage100TriggerAttribute(DataPercentage100TriggerAttribute dataPercentage100TriggerAttribute)
        {
            return new DataPercentage100TriggerAttributeCase().Set(dataPercentage100TriggerAttribute);
        }

        /// <summary>
        /// Method to match from the provided any-of cases. Here parameters
        /// represents the callback functions for any-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<NotificationGroupNameTriggerAttribute, T> notificationGroupNameTriggerAttribute,
            Func<ServicePlanTriggerAttribute, T> servicePlanTriggerAttribute,
            Func<DataPercentage50TriggerAttribute, T> dataPercentage50TriggerAttribute,
            Func<DataPercentage75TriggerAttribute, T> dataPercentage75TriggerAttribute,
            Func<DataPercentage90TriggerAttribute, T> dataPercentage90TriggerAttribute,
            Func<DataPercentage100TriggerAttribute, T> dataPercentage100TriggerAttribute);

        /// <summary>
        /// Method to match from the provided any-of cases. The parameters represent
        /// optional callback functions for any-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<NotificationGroupNameTriggerAttribute, T> notificationGroupNameTriggerAttribute = null,
            Func<ServicePlanTriggerAttribute, T> servicePlanTriggerAttribute = null,
            Func<DataPercentage50TriggerAttribute, T> dataPercentage50TriggerAttribute = null,
            Func<DataPercentage75TriggerAttribute, T> dataPercentage75TriggerAttribute = null,
            Func<DataPercentage90TriggerAttribute, T> dataPercentage90TriggerAttribute = null,
            Func<DataPercentage100TriggerAttribute, T> dataPercentage100TriggerAttribute = null) =>
                Match(notificationGroupNameTriggerAttribute, servicePlanTriggerAttribute, dataPercentage50TriggerAttribute, dataPercentage75TriggerAttribute, dataPercentage90TriggerAttribute, dataPercentage100TriggerAttribute);

        [JsonConverter(typeof(UnionTypeCaseConverter<NotificationGroupNameTriggerAttributeCase, NotificationGroupNameTriggerAttribute>))]
        private sealed class NotificationGroupNameTriggerAttributeCase : TriggerAttributesOptions2, ICaseValue<NotificationGroupNameTriggerAttributeCase, NotificationGroupNameTriggerAttribute>
        {
            public NotificationGroupNameTriggerAttribute Value;

            public override T Match<T>(
                Func<NotificationGroupNameTriggerAttribute, T> notificationGroupNameTriggerAttribute,
                Func<ServicePlanTriggerAttribute, T> servicePlanTriggerAttribute,
                Func<DataPercentage50TriggerAttribute, T> dataPercentage50TriggerAttribute,
                Func<DataPercentage75TriggerAttribute, T> dataPercentage75TriggerAttribute,
                Func<DataPercentage90TriggerAttribute, T> dataPercentage90TriggerAttribute,
                Func<DataPercentage100TriggerAttribute, T> dataPercentage100TriggerAttribute) =>
                   notificationGroupNameTriggerAttribute != null ? notificationGroupNameTriggerAttribute(Value) : default;

            public NotificationGroupNameTriggerAttributeCase Set(NotificationGroupNameTriggerAttribute value)
            {
                Value = value;
                return this;
            }

            public NotificationGroupNameTriggerAttribute Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is NotificationGroupNameTriggerAttributeCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ServicePlanTriggerAttributeCase, ServicePlanTriggerAttribute>))]
        private sealed class ServicePlanTriggerAttributeCase : TriggerAttributesOptions2, ICaseValue<ServicePlanTriggerAttributeCase, ServicePlanTriggerAttribute>
        {
            public ServicePlanTriggerAttribute Value;

            public override T Match<T>(
                Func<NotificationGroupNameTriggerAttribute, T> notificationGroupNameTriggerAttribute,
                Func<ServicePlanTriggerAttribute, T> servicePlanTriggerAttribute,
                Func<DataPercentage50TriggerAttribute, T> dataPercentage50TriggerAttribute,
                Func<DataPercentage75TriggerAttribute, T> dataPercentage75TriggerAttribute,
                Func<DataPercentage90TriggerAttribute, T> dataPercentage90TriggerAttribute,
                Func<DataPercentage100TriggerAttribute, T> dataPercentage100TriggerAttribute) =>
                   servicePlanTriggerAttribute != null ? servicePlanTriggerAttribute(Value) : default;

            public ServicePlanTriggerAttributeCase Set(ServicePlanTriggerAttribute value)
            {
                Value = value;
                return this;
            }

            public ServicePlanTriggerAttribute Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is ServicePlanTriggerAttributeCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<DataPercentage50TriggerAttributeCase, DataPercentage50TriggerAttribute>))]
        private sealed class DataPercentage50TriggerAttributeCase : TriggerAttributesOptions2, ICaseValue<DataPercentage50TriggerAttributeCase, DataPercentage50TriggerAttribute>
        {
            public DataPercentage50TriggerAttribute Value;

            public override T Match<T>(
                Func<NotificationGroupNameTriggerAttribute, T> notificationGroupNameTriggerAttribute,
                Func<ServicePlanTriggerAttribute, T> servicePlanTriggerAttribute,
                Func<DataPercentage50TriggerAttribute, T> dataPercentage50TriggerAttribute,
                Func<DataPercentage75TriggerAttribute, T> dataPercentage75TriggerAttribute,
                Func<DataPercentage90TriggerAttribute, T> dataPercentage90TriggerAttribute,
                Func<DataPercentage100TriggerAttribute, T> dataPercentage100TriggerAttribute) =>
                   dataPercentage50TriggerAttribute != null ? dataPercentage50TriggerAttribute(Value) : default;

            public DataPercentage50TriggerAttributeCase Set(DataPercentage50TriggerAttribute value)
            {
                Value = value;
                return this;
            }

            public DataPercentage50TriggerAttribute Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is DataPercentage50TriggerAttributeCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<DataPercentage75TriggerAttributeCase, DataPercentage75TriggerAttribute>))]
        private sealed class DataPercentage75TriggerAttributeCase : TriggerAttributesOptions2, ICaseValue<DataPercentage75TriggerAttributeCase, DataPercentage75TriggerAttribute>
        {
            public DataPercentage75TriggerAttribute Value;

            public override T Match<T>(
                Func<NotificationGroupNameTriggerAttribute, T> notificationGroupNameTriggerAttribute,
                Func<ServicePlanTriggerAttribute, T> servicePlanTriggerAttribute,
                Func<DataPercentage50TriggerAttribute, T> dataPercentage50TriggerAttribute,
                Func<DataPercentage75TriggerAttribute, T> dataPercentage75TriggerAttribute,
                Func<DataPercentage90TriggerAttribute, T> dataPercentage90TriggerAttribute,
                Func<DataPercentage100TriggerAttribute, T> dataPercentage100TriggerAttribute) =>
                   dataPercentage75TriggerAttribute != null ? dataPercentage75TriggerAttribute(Value) : default;

            public DataPercentage75TriggerAttributeCase Set(DataPercentage75TriggerAttribute value)
            {
                Value = value;
                return this;
            }

            public DataPercentage75TriggerAttribute Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is DataPercentage75TriggerAttributeCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<DataPercentage90TriggerAttributeCase, DataPercentage90TriggerAttribute>))]
        private sealed class DataPercentage90TriggerAttributeCase : TriggerAttributesOptions2, ICaseValue<DataPercentage90TriggerAttributeCase, DataPercentage90TriggerAttribute>
        {
            public DataPercentage90TriggerAttribute Value;

            public override T Match<T>(
                Func<NotificationGroupNameTriggerAttribute, T> notificationGroupNameTriggerAttribute,
                Func<ServicePlanTriggerAttribute, T> servicePlanTriggerAttribute,
                Func<DataPercentage50TriggerAttribute, T> dataPercentage50TriggerAttribute,
                Func<DataPercentage75TriggerAttribute, T> dataPercentage75TriggerAttribute,
                Func<DataPercentage90TriggerAttribute, T> dataPercentage90TriggerAttribute,
                Func<DataPercentage100TriggerAttribute, T> dataPercentage100TriggerAttribute) =>
                   dataPercentage90TriggerAttribute != null ? dataPercentage90TriggerAttribute(Value) : default;

            public DataPercentage90TriggerAttributeCase Set(DataPercentage90TriggerAttribute value)
            {
                Value = value;
                return this;
            }

            public DataPercentage90TriggerAttribute Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is DataPercentage90TriggerAttributeCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<DataPercentage100TriggerAttributeCase, DataPercentage100TriggerAttribute>))]
        private sealed class DataPercentage100TriggerAttributeCase : TriggerAttributesOptions2, ICaseValue<DataPercentage100TriggerAttributeCase, DataPercentage100TriggerAttribute>
        {
            public DataPercentage100TriggerAttribute Value;

            public override T Match<T>(
                Func<NotificationGroupNameTriggerAttribute, T> notificationGroupNameTriggerAttribute,
                Func<ServicePlanTriggerAttribute, T> servicePlanTriggerAttribute,
                Func<DataPercentage50TriggerAttribute, T> dataPercentage50TriggerAttribute,
                Func<DataPercentage75TriggerAttribute, T> dataPercentage75TriggerAttribute,
                Func<DataPercentage90TriggerAttribute, T> dataPercentage90TriggerAttribute,
                Func<DataPercentage100TriggerAttribute, T> dataPercentage100TriggerAttribute) =>
                   dataPercentage100TriggerAttribute != null ? dataPercentage100TriggerAttribute(Value) : default;

            public DataPercentage100TriggerAttributeCase Set(DataPercentage100TriggerAttribute value)
            {
                Value = value;
                return this;
            }

            public DataPercentage100TriggerAttribute Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is DataPercentage100TriggerAttributeCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }
    }
}