// <copyright file="HyperPreciseLocationResultException.cs" company="APIMatic">
// Verizon.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;
using Verizon.Standard.Http.Client;

namespace Verizon.Standard.Exceptions
{
    /// <summary>
    /// HyperPreciseLocationResultException.
    /// </summary>
    public class HyperPreciseLocationResultException : ApiException
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HyperPreciseLocationResultException"/> class.
        /// </summary>
        /// <param name="reason"> The reason for throwing exception.</param>
        /// <param name="context"> The HTTP context that encapsulates request and response objects.</param>
        public HyperPreciseLocationResultException(string reason, HttpContext context)
            : base(reason, context)
        {
        }

        /// <summary>
        /// Error Code.
        /// </summary>
        [JsonProperty("responseCode", NullValueHandling = NullValueHandling.Ignore)]
        public new Models.ErrorResponseCodeEnum? ResponseCode { get; set; }

        /// <summary>
        /// Error message.
        /// </summary>
        [JsonProperty("message", NullValueHandling = NullValueHandling.Ignore)]
        public new string Message { get; set; }

        /// <summary>
        /// Fault occurred while responding.
        /// </summary>
        [JsonProperty("fault", NullValueHandling = NullValueHandling.Ignore)]
        public Models.HyperPreciseLocationFault Fault { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"HyperPreciseLocationResultException : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            base.ToString(toStringOutput);
            toStringOutput.Add($"ResponseCode = {(this.ResponseCode == null ? "null" : this.ResponseCode.ToString())}");
            toStringOutput.Add($"Message = {this.Message ?? "null"}");
            toStringOutput.Add($"Fault = {(this.Fault == null ? "null" : this.Fault.ToString())}");
            toStringOutput.Add($"StackTrace = {(StackTrace != null ? $"\n{StackTrace}" : "null")}");
        }
    }
}